[package]
name = "toucan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "A reusable C header frontend without libclang"

[dependencies]
thiserror.workspace = true
serde.workspace = true
toucan_target = { version = "0.0.1", path = "../toucan_target" }
toucan_preprocessor = { version = "0.0.1", path = "../toucan_preprocessor" }
toucan_semantic = { version = "0.0.1", path = "../toucan_semantic" }
toucan_bindings = { version = "0.0.1", path = "../toucan_bindings" }

[dev-dependencies]
toucan_test_support = { version = "0.0.1", path = "../toucan_test_support" }
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
