[package]
name = "toucan_benchmark"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
bench = false
test = false
doctest = false

[features]
codspeed = ["dep:codspeed-criterion-compat"]

[dependencies]
codspeed-criterion-compat = { workspace = true, optional = true }
criterion.workspace = true
lang_c_reference = { package = "lang-c", version = "=0.15.1" }
regex = "1.13.1"
serde.workspace = true
serde_json.workspace = true
toucan_bindgen = { path = "../toucan_bindgen" }
toucan_parser = { path = "../toucan_parser" }
toucan_semantic = { path = "../toucan_semantic" }
toucan_target = { path = "../toucan_target" }

[[bench]]
name = "bindings"
harness = false

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "semantic"
harness = false

[lints]
workspace = true
