// Generated by Toucan for x86_64-unknown-linux-gnu.
// Do not edit.

#[cfg(not(all(target_arch = "x86_64", target_os = "linux", target_env = "gnu")))]
compile_error!("these C bindings were generated for a different target");

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_va_list_tag {
    pub gp_offset: ::core::ffi::c_uint,
    pub fp_offset: ::core::ffi::c_uint,
    pub overflow_arg_area: *mut ::core::ffi::c_void,
    pub reg_save_area: *mut ::core::ffi::c_void,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_va_list_tag>() == 24);
    assert!(::core::mem::align_of::<__toucan_va_list_tag>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_CCtx_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_DCtx_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_3 {
    pub error: size_t,
    pub lowerBound: ::core::ffi::c_int,
    pub upperBound: ::core::ffi::c_int,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_3>() == 16);
    assert!(::core::mem::align_of::<__toucan_record_3>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_inBuffer_s {
    pub src: *const ::core::ffi::c_void,
    pub size: size_t,
    pub pos: size_t,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_inBuffer_s>() == 24);
    assert!(::core::mem::align_of::<ZSTD_inBuffer_s>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_outBuffer_s {
    pub dst: *mut ::core::ffi::c_void,
    pub size: size_t,
    pub pos: size_t,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_outBuffer_s>() == 24);
    assert!(::core::mem::align_of::<ZSTD_outBuffer_s>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_CDict_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_DDict_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_8 {
    pub compressionLevel: ::core::ffi::c_int,
    pub notificationLevel: ::core::ffi::c_uint,
    pub dictID: ::core::ffi::c_uint,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_8>() == 12);
    assert!(::core::mem::align_of::<__toucan_record_8>() == 4);
};

#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_ErrorCode {
    ZSTD_error_no_error = 0,
    ZSTD_error_GENERIC = 1,
    ZSTD_error_prefix_unknown = 10,
    ZSTD_error_version_unsupported = 12,
    ZSTD_error_frameParameter_unsupported = 14,
    ZSTD_error_frameParameter_windowTooLarge = 16,
    ZSTD_error_corruption_detected = 20,
    ZSTD_error_checksum_wrong = 22,
    ZSTD_error_literals_headerWrong = 24,
    ZSTD_error_dictionary_corrupted = 30,
    ZSTD_error_dictionary_wrong = 32,
    ZSTD_error_dictionaryCreation_failed = 34,
    ZSTD_error_parameter_unsupported = 40,
    ZSTD_error_parameter_combination_unsupported = 41,
    ZSTD_error_parameter_outOfBound = 42,
    ZSTD_error_tableLog_tooLarge = 44,
    ZSTD_error_maxSymbolValue_tooLarge = 46,
    ZSTD_error_maxSymbolValue_tooSmall = 48,
    ZSTD_error_cannotProduce_uncompressedBlock = 49,
    ZSTD_error_stabilityCondition_notRespected = 50,
    ZSTD_error_stage_wrong = 60,
    ZSTD_error_init_missing = 62,
    ZSTD_error_memory_allocation = 64,
    ZSTD_error_workSpace_tooSmall = 66,
    ZSTD_error_dstSize_tooSmall = 70,
    ZSTD_error_srcSize_wrong = 72,
    ZSTD_error_dstBuffer_null = 74,
    ZSTD_error_noForwardProgress_destFull = 80,
    ZSTD_error_noForwardProgress_inputEmpty = 82,
    ZSTD_error_frameIndex_tooLarge = 100,
    ZSTD_error_seekableIO = 102,
    ZSTD_error_dstBuffer_wrong = 104,
    ZSTD_error_srcBuffer_wrong = 105,
    ZSTD_error_sequenceProducer_failed = 106,
    ZSTD_error_externalSequences_invalid = 107,
    ZSTD_error_maxCode = 120,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_ErrorCode>() == 4);
    assert!(::core::mem::align_of::<ZSTD_ErrorCode>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_strategy {
    ZSTD_fast = 1,
    ZSTD_dfast = 2,
    ZSTD_greedy = 3,
    ZSTD_lazy = 4,
    ZSTD_lazy2 = 5,
    ZSTD_btlazy2 = 6,
    ZSTD_btopt = 7,
    ZSTD_btultra = 8,
    ZSTD_btultra2 = 9,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_strategy>() == 4);
    assert!(::core::mem::align_of::<ZSTD_strategy>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_cParameter {
    ZSTD_c_compressionLevel = 100,
    ZSTD_c_windowLog = 101,
    ZSTD_c_hashLog = 102,
    ZSTD_c_chainLog = 103,
    ZSTD_c_searchLog = 104,
    ZSTD_c_minMatch = 105,
    ZSTD_c_targetLength = 106,
    ZSTD_c_strategy = 107,
    ZSTD_c_targetCBlockSize = 130,
    ZSTD_c_enableLongDistanceMatching = 160,
    ZSTD_c_ldmHashLog = 161,
    ZSTD_c_ldmMinMatch = 162,
    ZSTD_c_ldmBucketSizeLog = 163,
    ZSTD_c_ldmHashRateLog = 164,
    ZSTD_c_contentSizeFlag = 200,
    ZSTD_c_checksumFlag = 201,
    ZSTD_c_dictIDFlag = 202,
    ZSTD_c_nbWorkers = 400,
    ZSTD_c_jobSize = 401,
    ZSTD_c_overlapLog = 402,
    ZSTD_c_experimentalParam1 = 500,
    ZSTD_c_experimentalParam2 = 10,
    ZSTD_c_experimentalParam3 = 1000,
    ZSTD_c_experimentalParam4 = 1001,
    ZSTD_c_experimentalParam5 = 1002,
    ZSTD_c_experimentalParam7 = 1004,
    ZSTD_c_experimentalParam8 = 1005,
    ZSTD_c_experimentalParam9 = 1006,
    ZSTD_c_experimentalParam10 = 1007,
    ZSTD_c_experimentalParam11 = 1008,
    ZSTD_c_experimentalParam12 = 1009,
    ZSTD_c_experimentalParam13 = 1010,
    ZSTD_c_experimentalParam14 = 1011,
    ZSTD_c_experimentalParam15 = 1012,
    ZSTD_c_experimentalParam16 = 1013,
    ZSTD_c_experimentalParam17 = 1014,
    ZSTD_c_experimentalParam18 = 1015,
    ZSTD_c_experimentalParam19 = 1016,
    ZSTD_c_experimentalParam20 = 1017,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_cParameter>() == 4);
    assert!(::core::mem::align_of::<ZSTD_cParameter>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_ResetDirective {
    ZSTD_reset_session_only = 1,
    ZSTD_reset_parameters = 2,
    ZSTD_reset_session_and_parameters = 3,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_ResetDirective>() == 4);
    assert!(::core::mem::align_of::<ZSTD_ResetDirective>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_dParameter {
    ZSTD_d_windowLogMax = 100,
    ZSTD_d_experimentalParam1 = 1000,
    ZSTD_d_experimentalParam2 = 1001,
    ZSTD_d_experimentalParam3 = 1002,
    ZSTD_d_experimentalParam4 = 1003,
    ZSTD_d_experimentalParam5 = 1004,
    ZSTD_d_experimentalParam6 = 1005,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_dParameter>() == 4);
    assert!(::core::mem::align_of::<ZSTD_dParameter>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_EndDirective {
    ZSTD_e_continue = 0,
    ZSTD_e_flush = 1,
    ZSTD_e_end = 2,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_EndDirective>() == 4);
    assert!(::core::mem::align_of::<ZSTD_EndDirective>() == 4);
};
pub type ZDICT_params_t = __toucan_record_8;
pub type ZSTD_CCtx = ZSTD_CCtx_s;
pub type ZSTD_CDict = ZSTD_CDict_s;
pub type ZSTD_CStream = ZSTD_CCtx;
pub type ZSTD_DCtx = ZSTD_DCtx_s;
pub type ZSTD_DDict = ZSTD_DDict_s;
pub type ZSTD_DStream = ZSTD_DCtx;
pub type ZSTD_bounds = __toucan_record_3;
pub type ZSTD_inBuffer = ZSTD_inBuffer_s;
pub type ZSTD_outBuffer = ZSTD_outBuffer_s;
pub type ptrdiff_t = ::core::ffi::c_long;
pub type size_t = ::core::primitive::usize;
pub type wchar_t = ::core::ffi::c_int;
pub const ZSTD_btlazy2: ::core::primitive::u32 = 6;
pub const ZSTD_btopt: ::core::primitive::u32 = 7;
pub const ZSTD_btultra: ::core::primitive::u32 = 8;
pub const ZSTD_btultra2: ::core::primitive::u32 = 9;
pub const ZSTD_c_chainLog: ::core::primitive::u32 = 103;
pub const ZSTD_c_checksumFlag: ::core::primitive::u32 = 201;
pub const ZSTD_c_compressionLevel: ::core::primitive::u32 = 100;
pub const ZSTD_c_contentSizeFlag: ::core::primitive::u32 = 200;
pub const ZSTD_c_dictIDFlag: ::core::primitive::u32 = 202;
pub const ZSTD_c_enableLongDistanceMatching: ::core::primitive::u32 = 160;
pub const ZSTD_c_experimentalParam1: ::core::primitive::u32 = 500;
pub const ZSTD_c_experimentalParam10: ::core::primitive::u32 = 1007;
pub const ZSTD_c_experimentalParam11: ::core::primitive::u32 = 1008;
pub const ZSTD_c_experimentalParam12: ::core::primitive::u32 = 1009;
pub const ZSTD_c_experimentalParam13: ::core::primitive::u32 = 1010;
pub const ZSTD_c_experimentalParam14: ::core::primitive::u32 = 1011;
pub const ZSTD_c_experimentalParam15: ::core::primitive::u32 = 1012;
pub const ZSTD_c_experimentalParam16: ::core::primitive::u32 = 1013;
pub const ZSTD_c_experimentalParam17: ::core::primitive::u32 = 1014;
pub const ZSTD_c_experimentalParam18: ::core::primitive::u32 = 1015;
pub const ZSTD_c_experimentalParam19: ::core::primitive::u32 = 1016;
pub const ZSTD_c_experimentalParam2: ::core::primitive::u32 = 10;
pub const ZSTD_c_experimentalParam20: ::core::primitive::u32 = 1017;
pub const ZSTD_c_experimentalParam3: ::core::primitive::u32 = 1000;
pub const ZSTD_c_experimentalParam4: ::core::primitive::u32 = 1001;
pub const ZSTD_c_experimentalParam5: ::core::primitive::u32 = 1002;
pub const ZSTD_c_experimentalParam7: ::core::primitive::u32 = 1004;
pub const ZSTD_c_experimentalParam8: ::core::primitive::u32 = 1005;
pub const ZSTD_c_experimentalParam9: ::core::primitive::u32 = 1006;
pub const ZSTD_c_hashLog: ::core::primitive::u32 = 102;
pub const ZSTD_c_jobSize: ::core::primitive::u32 = 401;
pub const ZSTD_c_ldmBucketSizeLog: ::core::primitive::u32 = 163;
pub const ZSTD_c_ldmHashLog: ::core::primitive::u32 = 161;
pub const ZSTD_c_ldmHashRateLog: ::core::primitive::u32 = 164;
pub const ZSTD_c_ldmMinMatch: ::core::primitive::u32 = 162;
pub const ZSTD_c_minMatch: ::core::primitive::u32 = 105;
pub const ZSTD_c_nbWorkers: ::core::primitive::u32 = 400;
pub const ZSTD_c_overlapLog: ::core::primitive::u32 = 402;
pub const ZSTD_c_searchLog: ::core::primitive::u32 = 104;
pub const ZSTD_c_strategy: ::core::primitive::u32 = 107;
pub const ZSTD_c_targetCBlockSize: ::core::primitive::u32 = 130;
pub const ZSTD_c_targetLength: ::core::primitive::u32 = 106;
pub const ZSTD_c_windowLog: ::core::primitive::u32 = 101;
pub const ZSTD_d_experimentalParam1: ::core::primitive::u32 = 1000;
pub const ZSTD_d_experimentalParam2: ::core::primitive::u32 = 1001;
pub const ZSTD_d_experimentalParam3: ::core::primitive::u32 = 1002;
pub const ZSTD_d_experimentalParam4: ::core::primitive::u32 = 1003;
pub const ZSTD_d_experimentalParam5: ::core::primitive::u32 = 1004;
pub const ZSTD_d_experimentalParam6: ::core::primitive::u32 = 1005;
pub const ZSTD_d_windowLogMax: ::core::primitive::u32 = 100;
pub const ZSTD_dfast: ::core::primitive::u32 = 2;
pub const ZSTD_e_continue: ::core::primitive::u32 = 0;
pub const ZSTD_e_end: ::core::primitive::u32 = 2;
pub const ZSTD_e_flush: ::core::primitive::u32 = 1;
pub const ZSTD_error_GENERIC: ::core::primitive::u32 = 1;
pub const ZSTD_error_cannotProduce_uncompressedBlock: ::core::primitive::u32 = 49;
pub const ZSTD_error_checksum_wrong: ::core::primitive::u32 = 22;
pub const ZSTD_error_corruption_detected: ::core::primitive::u32 = 20;
pub const ZSTD_error_dictionaryCreation_failed: ::core::primitive::u32 = 34;
pub const ZSTD_error_dictionary_corrupted: ::core::primitive::u32 = 30;
pub const ZSTD_error_dictionary_wrong: ::core::primitive::u32 = 32;
pub const ZSTD_error_dstBuffer_null: ::core::primitive::u32 = 74;
pub const ZSTD_error_dstBuffer_wrong: ::core::primitive::u32 = 104;
pub const ZSTD_error_dstSize_tooSmall: ::core::primitive::u32 = 70;
pub const ZSTD_error_externalSequences_invalid: ::core::primitive::u32 = 107;
pub const ZSTD_error_frameIndex_tooLarge: ::core::primitive::u32 = 100;
pub const ZSTD_error_frameParameter_unsupported: ::core::primitive::u32 = 14;
pub const ZSTD_error_frameParameter_windowTooLarge: ::core::primitive::u32 = 16;
pub const ZSTD_error_init_missing: ::core::primitive::u32 = 62;
pub const ZSTD_error_literals_headerWrong: ::core::primitive::u32 = 24;
pub const ZSTD_error_maxCode: ::core::primitive::u32 = 120;
pub const ZSTD_error_maxSymbolValue_tooLarge: ::core::primitive::u32 = 46;
pub const ZSTD_error_maxSymbolValue_tooSmall: ::core::primitive::u32 = 48;
pub const ZSTD_error_memory_allocation: ::core::primitive::u32 = 64;
pub const ZSTD_error_noForwardProgress_destFull: ::core::primitive::u32 = 80;
pub const ZSTD_error_noForwardProgress_inputEmpty: ::core::primitive::u32 = 82;
pub const ZSTD_error_no_error: ::core::primitive::u32 = 0;
pub const ZSTD_error_parameter_combination_unsupported: ::core::primitive::u32 = 41;
pub const ZSTD_error_parameter_outOfBound: ::core::primitive::u32 = 42;
pub const ZSTD_error_parameter_unsupported: ::core::primitive::u32 = 40;
pub const ZSTD_error_prefix_unknown: ::core::primitive::u32 = 10;
pub const ZSTD_error_seekableIO: ::core::primitive::u32 = 102;
pub const ZSTD_error_sequenceProducer_failed: ::core::primitive::u32 = 106;
pub const ZSTD_error_srcBuffer_wrong: ::core::primitive::u32 = 105;
pub const ZSTD_error_srcSize_wrong: ::core::primitive::u32 = 72;
pub const ZSTD_error_stabilityCondition_notRespected: ::core::primitive::u32 = 50;
pub const ZSTD_error_stage_wrong: ::core::primitive::u32 = 60;
pub const ZSTD_error_tableLog_tooLarge: ::core::primitive::u32 = 44;
pub const ZSTD_error_version_unsupported: ::core::primitive::u32 = 12;
pub const ZSTD_error_workSpace_tooSmall: ::core::primitive::u32 = 66;
pub const ZSTD_fast: ::core::primitive::u32 = 1;
pub const ZSTD_greedy: ::core::primitive::u32 = 3;
pub const ZSTD_lazy: ::core::primitive::u32 = 4;
pub const ZSTD_lazy2: ::core::primitive::u32 = 5;
pub const ZSTD_reset_parameters: ::core::primitive::u32 = 2;
pub const ZSTD_reset_session_and_parameters: ::core::primitive::u32 = 3;
pub const ZSTD_reset_session_only: ::core::primitive::u32 = 1;

extern "C" {
    pub fn ZSTD_getErrorString(arg0: ZSTD_ErrorCode) -> *const ::core::ffi::c_char;
    pub fn ZSTD_versionNumber() -> ::core::ffi::c_uint;
    pub fn ZSTD_versionString() -> *const ::core::ffi::c_char;
    pub fn ZSTD_compress(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: size_t, arg4: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_decompress(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: size_t) -> size_t;
    pub fn ZSTD_getFrameContentSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_ulonglong;
    pub fn ZSTD_getDecompressedSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_ulonglong;
    pub fn ZSTD_findFrameCompressedSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> size_t;
    pub fn ZSTD_compressBound(arg0: size_t) -> size_t;
    pub fn ZSTD_isError(arg0: size_t) -> ::core::ffi::c_uint;
    pub fn ZSTD_getErrorCode(arg0: size_t) -> ZSTD_ErrorCode;
    pub fn ZSTD_getErrorName(arg0: size_t) -> *const ::core::ffi::c_char;
    pub fn ZSTD_minCLevel() -> ::core::ffi::c_int;
    pub fn ZSTD_maxCLevel() -> ::core::ffi::c_int;
    pub fn ZSTD_defaultCLevel() -> ::core::ffi::c_int;
    pub fn ZSTD_createCCtx() -> *mut ZSTD_CCtx;
    pub fn ZSTD_freeCCtx(arg0: *mut ZSTD_CCtx) -> size_t;
    pub fn ZSTD_compressCCtx(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_createDCtx() -> *mut ZSTD_DCtx;
    pub fn ZSTD_freeDCtx(arg0: *mut ZSTD_DCtx) -> size_t;
    pub fn ZSTD_decompressDCtx(arg0: *mut ZSTD_DCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_cParam_getBounds(arg0: ZSTD_cParameter) -> ZSTD_bounds;
    pub fn ZSTD_CCtx_setParameter(arg0: *mut ZSTD_CCtx, arg1: ZSTD_cParameter, arg2: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_CCtx_setPledgedSrcSize(arg0: *mut ZSTD_CCtx, arg1: ::core::ffi::c_ulonglong) -> size_t;
    pub fn ZSTD_CCtx_reset(arg0: *mut ZSTD_CCtx, arg1: ZSTD_ResetDirective) -> size_t;
    pub fn ZSTD_compress2(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_dParam_getBounds(arg0: ZSTD_dParameter) -> ZSTD_bounds;
    pub fn ZSTD_DCtx_setParameter(arg0: *mut ZSTD_DCtx, arg1: ZSTD_dParameter, arg2: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_DCtx_reset(arg0: *mut ZSTD_DCtx, arg1: ZSTD_ResetDirective) -> size_t;
    pub fn ZSTD_createCStream() -> *mut ZSTD_CStream;
    pub fn ZSTD_freeCStream(arg0: *mut ZSTD_CStream) -> size_t;
    pub fn ZSTD_compressStream2(arg0: *mut ZSTD_CCtx, arg1: *mut ZSTD_outBuffer, arg2: *mut ZSTD_inBuffer, arg3: ZSTD_EndDirective) -> size_t;
    pub fn ZSTD_CStreamInSize() -> size_t;
    pub fn ZSTD_CStreamOutSize() -> size_t;
    pub fn ZSTD_initCStream(arg0: *mut ZSTD_CStream, arg1: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_compressStream(arg0: *mut ZSTD_CStream, arg1: *mut ZSTD_outBuffer, arg2: *mut ZSTD_inBuffer) -> size_t;
    pub fn ZSTD_flushStream(arg0: *mut ZSTD_CStream, arg1: *mut ZSTD_outBuffer) -> size_t;
    pub fn ZSTD_endStream(arg0: *mut ZSTD_CStream, arg1: *mut ZSTD_outBuffer) -> size_t;
    pub fn ZSTD_createDStream() -> *mut ZSTD_DStream;
    pub fn ZSTD_freeDStream(arg0: *mut ZSTD_DStream) -> size_t;
    pub fn ZSTD_initDStream(arg0: *mut ZSTD_DStream) -> size_t;
    pub fn ZSTD_decompressStream(arg0: *mut ZSTD_DStream, arg1: *mut ZSTD_outBuffer, arg2: *mut ZSTD_inBuffer) -> size_t;
    pub fn ZSTD_DStreamInSize() -> size_t;
    pub fn ZSTD_DStreamOutSize() -> size_t;
    pub fn ZSTD_compress_usingDict(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ::core::ffi::c_void, arg6: size_t, arg7: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_decompress_usingDict(arg0: *mut ZSTD_DCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ::core::ffi::c_void, arg6: size_t) -> size_t;
    pub fn ZSTD_createCDict(arg0: *const ::core::ffi::c_void, arg1: size_t, arg2: ::core::ffi::c_int) -> *mut ZSTD_CDict;
    pub fn ZSTD_freeCDict(arg0: *mut ZSTD_CDict) -> size_t;
    pub fn ZSTD_compress_usingCDict(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ZSTD_CDict) -> size_t;
    pub fn ZSTD_createDDict(arg0: *const ::core::ffi::c_void, arg1: size_t) -> *mut ZSTD_DDict;
    pub fn ZSTD_freeDDict(arg0: *mut ZSTD_DDict) -> size_t;
    pub fn ZSTD_decompress_usingDDict(arg0: *mut ZSTD_DCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ZSTD_DDict) -> size_t;
    pub fn ZSTD_getDictID_fromDict(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_uint;
    pub fn ZSTD_getDictID_fromCDict(arg0: *const ZSTD_CDict) -> ::core::ffi::c_uint;
    pub fn ZSTD_getDictID_fromDDict(arg0: *const ZSTD_DDict) -> ::core::ffi::c_uint;
    pub fn ZSTD_getDictID_fromFrame(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_uint;
    pub fn ZSTD_CCtx_loadDictionary(arg0: *mut ZSTD_CCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_CCtx_refCDict(arg0: *mut ZSTD_CCtx, arg1: *const ZSTD_CDict) -> size_t;
    pub fn ZSTD_CCtx_refPrefix(arg0: *mut ZSTD_CCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_DCtx_loadDictionary(arg0: *mut ZSTD_DCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_DCtx_refDDict(arg0: *mut ZSTD_DCtx, arg1: *const ZSTD_DDict) -> size_t;
    pub fn ZSTD_DCtx_refPrefix(arg0: *mut ZSTD_DCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_sizeof_CCtx(arg0: *const ZSTD_CCtx) -> size_t;
    pub fn ZSTD_sizeof_DCtx(arg0: *const ZSTD_DCtx) -> size_t;
    pub fn ZSTD_sizeof_CStream(arg0: *const ZSTD_CStream) -> size_t;
    pub fn ZSTD_sizeof_DStream(arg0: *const ZSTD_DStream) -> size_t;
    pub fn ZSTD_sizeof_CDict(arg0: *const ZSTD_CDict) -> size_t;
    pub fn ZSTD_sizeof_DDict(arg0: *const ZSTD_DDict) -> size_t;
    pub fn ZDICT_trainFromBuffer(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: *const size_t, arg4: ::core::ffi::c_uint) -> size_t;
    pub fn ZDICT_finalizeDictionary(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: size_t, arg4: *const ::core::ffi::c_void, arg5: *const size_t, arg6: ::core::ffi::c_uint, arg7: ZDICT_params_t) -> size_t;
    pub fn ZDICT_getDictID(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_uint;
    pub fn ZDICT_getDictHeaderSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> size_t;
    pub fn ZDICT_isError(arg0: size_t) -> ::core::ffi::c_uint;
    pub fn ZDICT_getErrorName(arg0: size_t) -> *const ::core::ffi::c_char;
}
pub const ZSTD_BLOCKSIZELOG_MAX: ::core::primitive::u32 = 17;
pub const ZSTD_BLOCKSIZE_MAX: ::core::primitive::u32 = 131072;
pub const ZSTD_CLEVEL_DEFAULT: ::core::primitive::u32 = 3;
pub const ZSTD_CONTENTSIZE_ERROR: ::core::primitive::u64 = 18446744073709551614;
pub const ZSTD_CONTENTSIZE_UNKNOWN: ::core::primitive::u64 = 18446744073709551615;
pub const ZSTD_MAGICNUMBER: ::core::primitive::u32 = 4247762216;
pub const ZSTD_MAGIC_DICTIONARY: ::core::primitive::u32 = 3962610743;
pub const ZSTD_MAGIC_SKIPPABLE_MASK: ::core::primitive::u32 = 4294967280;
pub const ZSTD_MAGIC_SKIPPABLE_START: ::core::primitive::u32 = 407710288;
pub const ZSTD_MAX_INPUT_SIZE: ::core::primitive::u64 = 18374966859414961920;
pub const ZSTD_VERSION_MAJOR: ::core::primitive::u32 = 1;
pub const ZSTD_VERSION_MINOR: ::core::primitive::u32 = 5;
pub const ZSTD_VERSION_NUMBER: ::core::primitive::u32 = 10507;
pub const ZSTD_VERSION_RELEASE: ::core::primitive::u32 = 7;
pub const ZSTD_VERSION_STRING: &[::core::primitive::u8; 6] = &[49, 46, 53, 46, 55, 0];
pub const _LP64: ::core::primitive::u32 = 1;
pub const linux: ::core::primitive::u32 = 1;
pub const unix: ::core::primitive::u32 = 1;
