//! Deterministic Rust bindings from analyzed C declarations.
//!
//! Every emitted record uses its fields' Rust representations. Constructs whose
//! calling ABI cannot be represented are errors, including bitfields passed by
//! value, field-level alignment, and long double. Incomplete records and records
//! containing bitfields are available behind pointers.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use toucan_semantic::{
    DeclarationKind, FloatKind, FunctionType, IntegerKind, IntegerValue, RecordKind, Scope,
    TranslationUnit, Type, TypeKind,
};

#[derive(Debug, Default, Clone)]
pub struct Options {
    /// Exact names or prefixes ending in `*`. Empty selects all declarations.
    pub allowlist: Vec<String>,
}

impl Options {
    pub fn includes(&self, name: &str) -> bool {
        self.allowlist.is_empty()
            || self.allowlist.iter().any(|pattern| {
                pattern
                    .strip_suffix('*')
                    .map_or(pattern == name, |prefix| name.starts_with(prefix))
            })
    }
}

#[derive(Debug)]
pub struct Bindings {
    pub source: String,
    pub declarations: usize,
    /// Internal-linkage declarations are not callable through external bindings.
    pub skipped: Vec<String>,
}

#[derive(Debug, thiserror::Error)]
#[error("{0}")]
pub struct Error(pub String);

impl From<toucan_semantic::Error> for Error {
    fn from(error: toucan_semantic::Error) -> Self {
        Self(error.to_string())
    }
}

/// Generate a module suitable for `include!`, without process-global attributes.
pub fn generate(unit: &TranslationUnit, options: &Options) -> Result<Bindings, Error> {
    let mut emitter = Emitter {
        unit,
        names: Names::new(
            unit.declarations
                .iter()
                .map(|item| item.name.as_str())
                .chain(unit.typedefs.keys().map(String::as_str))
                .chain(unit.constants.keys().map(String::as_str))
                .chain(
                    unit.records
                        .iter()
                        .filter(|item| item.scope == Scope::File)
                        .filter_map(|item| item.name.as_deref()),
                )
                .chain(
                    unit.enums
                        .iter()
                        .filter(|item| item.scope == Scope::File)
                        .filter_map(|item| item.name.as_deref()),
                ),
        ),
        records: BTreeSet::new(),
        enums: BTreeSet::new(),
        aliases: BTreeSet::new(),
    };
    let mut selected = Vec::new();
    let mut skipped = Vec::new();
    let mut seen = BTreeSet::new();
    for declaration in &unit.declarations {
        if !options.includes(&declaration.name) || !seen.insert(declaration.name.clone()) {
            continue;
        }
        if declaration.is_static
            || (declaration.kind == DeclarationKind::Function && declaration.is_definition)
        {
            skipped.push(declaration.name.clone());
            continue;
        }
        if declaration.kind == DeclarationKind::Typedef {
            emitter.collect(&Type::new(TypeKind::Typedef(declaration.name.clone())))?;
        } else {
            emitter.collect(&declaration.ty)?;
        }
        selected.push(declaration);
    }
    for (id, record) in unit.records.iter().enumerate() {
        if record.scope == Scope::File
            && record
                .name
                .as_ref()
                .is_some_and(|name| options.includes(name))
        {
            emitter.collect(&Type::new(TypeKind::Record(id)))?;
        }
    }
    for (id, enumeration) in unit.enums.iter().enumerate() {
        if enumeration.scope == Scope::File
            && enumeration
                .name
                .as_ref()
                .is_some_and(|name| options.includes(name))
        {
            emitter.enums.insert(id);
        }
    }
    let mut source = format!(
        "// Generated by Toucan for {}.\n// Do not edit.\n\n",
        unit.target.triple()
    );
    let (arch, os) = match unit.target.triple() {
        "x86_64-unknown-linux-gnu" => ("x86_64", "linux"),
        "aarch64-unknown-linux-gnu" => ("aarch64", "linux"),
        "x86_64-apple-darwin" => ("x86_64", "macos"),
        "aarch64-apple-darwin" => ("aarch64", "macos"),
        "x86_64-pc-windows-msvc" => ("x86_64", "windows"),
        triple => return Err(Error(format!("binding target `{triple}` is unsupported"))),
    };
    let environment = match os {
        "linux" => ", target_env = \"gnu\"",
        "windows" => ", target_env = \"msvc\"",
        _ => "",
    };
    writeln!(source, "#[cfg(not(all(target_arch = {arch:?}, target_os = {os:?}{environment})))]\ncompile_error!(\"these C bindings were generated for a different target\");\n").unwrap();
    for &id in &emitter.records {
        emitter.record(id, &mut source)?;
    }
    for &id in &emitter.enums {
        writeln!(
            source,
            "pub type {} = {};",
            emitter.enum_name(id)?,
            emitter.enum_type(id)?
        )
        .unwrap();
    }
    for name in &emitter.aliases {
        let ty = unit
            .typedefs
            .get(name)
            .ok_or_else(|| Error(format!("missing typedef `{name}`")))?;
        let rust_name = emitter.names.identifier(name)?;
        let rust_type = if let TypeKind::Function(function) = &unit.resolve(ty)?.kind {
            emitter.check_function(function)?;
            format!("unsafe extern \"C\" fn{}", emitter.signature(function)?)
        } else {
            emitter.ty(ty)?
        };
        if rust_name != rust_type {
            writeln!(source, "pub type {rust_name} = {rust_type};").unwrap();
        }
    }
    for (name, value) in &unit.constants {
        if options.includes(name) {
            source.push_str(&integer_constant_named(
                &emitter.names.identifier(name)?,
                *value,
            )?);
        }
    }
    source.push_str("\nunsafe extern \"C\" {\n");
    for declaration in &selected {
        let name = emitter.names.identifier(&declaration.name)?;
        match declaration.kind {
            DeclarationKind::Typedef => {}
            DeclarationKind::Function => {
                let TypeKind::Function(function) = &unit.resolve(&declaration.ty)?.kind else {
                    return Err(Error(format!("`{name}` is not a function")));
                };
                emitter.check_function(function)?;
                let link_name = declaration.link_name.as_ref().unwrap_or(&declaration.name);
                if name != *link_name {
                    writeln!(source, "    #[link_name = {link_name:?}]").unwrap();
                }
                writeln!(source, "    pub fn {name}{};", emitter.signature(function)?).unwrap();
            }
            DeclarationKind::Variable => {
                let link_name = declaration.link_name.as_ref().unwrap_or(&declaration.name);
                if name != *link_name {
                    writeln!(source, "    #[link_name = {link_name:?}]").unwrap();
                }
                let mutable = if emitter.is_const(&declaration.ty)? {
                    ""
                } else {
                    "mut "
                };
                writeln!(
                    source,
                    "    pub static {mutable}{name}: {};",
                    emitter.ty(&declaration.ty)?
                )
                .unwrap();
            }
        }
    }
    source.push_str("}\n");
    Ok(Bindings {
        source,
        declarations: selected.len(),
        skipped,
    })
}

/// Format a target-typed constant without host-width conversions.
pub fn integer_constant(name: &str, value: IntegerValue) -> Result<String, Error> {
    integer_constant_named(&identifier(name)?, value)
}

fn integer_constant_named(name: &str, value: IntegerValue) -> Result<String, Error> {
    if ![8, 16, 32, 64, 128].contains(&value.bits) {
        return Err(Error("unsupported integer width".into()));
    }
    if value.bits < 128 && value.value >= (1u128 << value.bits) {
        return Err(Error("integer constant exceeds its declared width".into()));
    }
    let prefix = if value.signed { 'i' } else { 'u' };
    let literal = if value.signed {
        value.signed_value().to_string()
    } else {
        value.value.to_string()
    };
    Ok(format!(
        "pub const {name}: ::core::primitive::{prefix}{} = {literal};\n",
        value.bits
    ))
}

struct Emitter<'a> {
    unit: &'a TranslationUnit,
    names: Names,
    records: BTreeSet<usize>,
    enums: BTreeSet<usize>,
    aliases: BTreeSet<String>,
}

struct BitfieldSegment {
    start: u64,
    end: u64,
    fields: Vec<(usize, toucan_target::FieldLayout)>,
}

impl Emitter<'_> {
    fn collect(&mut self, ty: &Type) -> Result<(), Error> {
        self.collect_at(ty, 0)
    }

    fn collect_at(&mut self, ty: &Type, depth: usize) -> Result<(), Error> {
        if depth >= 256 {
            return Err(Error(
                "type nesting exceeds the binding limit of 256".into(),
            ));
        }
        match &ty.kind {
            TypeKind::Typedef(name) => {
                if self.aliases.insert(name.clone()) {
                    let ty = self
                        .unit
                        .typedefs
                        .get(name)
                        .ok_or_else(|| Error(format!("unknown typedef `{name}`")))?;
                    self.collect_at(ty, depth + 1)?;
                }
            }
            TypeKind::Record(id) => {
                if self.records.insert(*id) {
                    let record = self
                        .unit
                        .records
                        .get(*id)
                        .ok_or_else(|| Error("invalid record identity".into()))?;
                    if let Some(fields) = &record.fields {
                        for field in fields {
                            self.collect_at(&field.ty, depth + 1)?;
                        }
                    }
                }
            }
            TypeKind::Enum(id) => {
                if self.unit.enums.get(*id).is_none() {
                    return Err(Error("invalid enum identity".into()));
                }
                self.enums.insert(*id);
            }
            TypeKind::Pointer(pointee)
            | TypeKind::Array {
                element: pointee, ..
            } => self.collect_at(pointee, depth + 1)?,
            TypeKind::Function(function) => {
                self.collect_at(&function.return_type, depth + 1)?;
                for parameter in &function.parameters {
                    self.collect_at(&parameter.ty, depth + 1)?;
                }
            }
            _ => {}
        }
        Ok(())
    }

    fn record_name(&self, id: usize) -> Result<String, Error> {
        let record = self
            .unit
            .records
            .get(id)
            .ok_or_else(|| Error("invalid record identity".into()))?;
        if record.scope == Scope::File
            && let Some(name) = &record.name
        {
            let collision = self
                .unit
                .typedefs
                .get(name)
                .map(|ty| self.unit.resolve(ty))
                .transpose()?
                .is_some_and(|ty| ty.kind != TypeKind::Record(id));
            let repeated = self.unit.records[..id]
                .iter()
                .any(|record| record.scope == Scope::File && record.name.as_ref() == Some(name));
            if !collision && !repeated {
                return self.names.identifier(name);
            }
        }
        self.synthetic_name(&format!("__toucan_record_{id}"))
    }

    fn enum_name(&self, id: usize) -> Result<String, Error> {
        let enumeration = self
            .unit
            .enums
            .get(id)
            .ok_or_else(|| Error("invalid enum identity".into()))?;
        if enumeration.scope == Scope::File
            && let Some(name) = &enumeration.name
        {
            let collision = self
                .unit
                .typedefs
                .get(name)
                .map(|ty| self.unit.resolve(ty))
                .transpose()?
                .is_some_and(|ty| ty.kind != TypeKind::Enum(id));
            let repeated = self.unit.enums[..id].iter().any(|enumeration| {
                enumeration.scope == Scope::File && enumeration.name.as_ref() == Some(name)
            });
            if !collision && !repeated {
                return self.names.identifier(name);
            }
        }
        self.synthetic_name(&format!("__toucan_enum_{id}"))
    }

    fn synthetic_name(&self, stem: &str) -> Result<String, Error> {
        let mut candidate = stem.to_owned();
        while self.unit.typedefs.contains_key(&candidate)
            || self
                .unit
                .declarations
                .iter()
                .any(|item| item.name == candidate)
            || self
                .unit
                .records
                .iter()
                .any(|item| item.scope == Scope::File && item.name.as_ref() == Some(&candidate))
            || self
                .unit
                .enums
                .iter()
                .any(|item| item.scope == Scope::File && item.name.as_ref() == Some(&candidate))
        {
            candidate.push('_');
        }
        identifier(&candidate)
    }

    fn enum_type(&self, id: usize) -> Result<String, Error> {
        let layout = self.unit.layout(&Type::new(TypeKind::Enum(id)))?;
        let signed = self.unit.target.triple().contains("msvc")
            || self.unit.enums[id]
                .variants
                .iter()
                .any(|v| v.value.signed && v.value.signed_value() < 0);
        Ok(format!(
            "::core::primitive::{}{}",
            if signed { 'i' } else { 'u' },
            layout.size_bits
        ))
    }

    fn is_const(&self, ty: &Type) -> Result<bool, Error> {
        let mut ty = ty;
        let mut visited = BTreeSet::new();
        loop {
            if ty.qualifiers.is_const {
                return Ok(true);
            }
            if let TypeKind::Array { element, .. } = &ty.kind {
                ty = element;
                continue;
            }
            let TypeKind::Typedef(name) = &ty.kind else {
                return Ok(false);
            };
            if !visited.insert(name) {
                return Err(Error("cyclic typedef".into()));
            }
            ty = self
                .unit
                .typedefs
                .get(name)
                .ok_or_else(|| Error(format!("unknown typedef `{name}`")))?;
        }
    }

    fn ty(&self, ty: &Type) -> Result<String, Error> {
        self.ty_at(ty, 0)
    }

    fn ty_at(&self, ty: &Type, depth: usize) -> Result<String, Error> {
        check_depth(depth)?;
        Ok(match &ty.kind {
            TypeKind::Void => "::core::ffi::c_void".into(),
            TypeKind::Bool => "::core::primitive::bool".into(),
            TypeKind::Integer(IntegerKind::Int128) => "::core::primitive::i128".into(),
            TypeKind::Integer(IntegerKind::UnsignedInt128) => "::core::primitive::u128".into(),
            TypeKind::Integer(kind) => format!(
                "::core::ffi::{}",
                match kind {
                    IntegerKind::Char => "c_char",
                    IntegerKind::SignedChar => "c_schar",
                    IntegerKind::UnsignedChar => "c_uchar",
                    IntegerKind::Short => "c_short",
                    IntegerKind::UnsignedShort => "c_ushort",
                    IntegerKind::Int => "c_int",
                    IntegerKind::UnsignedInt => "c_uint",
                    IntegerKind::Long => "c_long",
                    IntegerKind::UnsignedLong => "c_ulong",
                    IntegerKind::LongLong => "c_longlong",
                    IntegerKind::UnsignedLongLong => "c_ulonglong",
                    IntegerKind::Int128 | IntegerKind::UnsignedInt128 =>
                        unreachable!("handled above"),
                }
            ),
            TypeKind::Float(FloatKind::Float) => "::core::primitive::f32".into(),
            TypeKind::Float(FloatKind::Double) => "::core::primitive::f64".into(),
            TypeKind::Float(FloatKind::Extended { .. }) => {
                return Err(Error(
                    "extended floating-point types have no supported Rust ABI representation"
                        .into(),
                ));
            }
            TypeKind::Float(FloatKind::LongDouble) => {
                return Err(Error(
                    "long double has no supported Rust ABI representation".into(),
                ));
            }
            TypeKind::Pointer(pointee) => {
                if let TypeKind::Function(function) = &self.unit.resolve(pointee)?.kind {
                    self.check_function_at(function, depth + 1)?;
                    format!(
                        "::core::option::Option<unsafe extern \"C\" fn{}>",
                        self.signature_at(function, depth + 1)?
                    )
                } else {
                    format!(
                        "*{} {}",
                        if self.is_const(pointee)? {
                            "const"
                        } else {
                            "mut"
                        },
                        self.ty_at(pointee, depth + 1)?
                    )
                }
            }
            TypeKind::Array { element, length } => {
                format!(
                    "[{}; {}]",
                    self.ty_at(element, depth + 1)?,
                    length.unwrap_or(0)
                )
            }
            TypeKind::Function(_) => {
                return Err(Error("bare function type requires a pointer".into()));
            }
            TypeKind::Record(id) => self.record_name(*id)?,
            TypeKind::Enum(id) => self.enum_name(*id)?,
            TypeKind::Typedef(name) => {
                // A C function typedef denotes the function, not a nullable pointer.
                if let TypeKind::Function(function) = &self.unit.resolve(ty)?.kind {
                    self.check_function_at(function, depth + 1)?;
                    format!(
                        "unsafe extern \"C\" fn{}",
                        self.signature_at(function, depth + 1)?
                    )
                } else {
                    self.names.identifier(name)?
                }
            }
        })
    }

    fn signature(&self, function: &FunctionType) -> Result<String, Error> {
        self.signature_at(function, 0)
    }

    fn signature_at(&self, function: &FunctionType, depth: usize) -> Result<String, Error> {
        check_depth(depth)?;
        let mut args = Vec::new();
        for (i, parameter) in function.parameters.iter().enumerate() {
            // Position-based names avoid duplicate or Rust-reserved C parameter names.
            args.push(format!("arg{i}: {}", self.ty_at(&parameter.ty, depth + 1)?));
        }
        if function.variadic {
            args.push("...".into());
        }
        let result = if matches!(
            self.unit.resolve(&function.return_type)?.kind,
            TypeKind::Void
        ) {
            String::new()
        } else {
            format!(" -> {}", self.ty_at(&function.return_type, depth + 1)?)
        };
        Ok(format!("({}){result}", args.join(", ")))
    }

    fn check_function(&self, function: &FunctionType) -> Result<(), Error> {
        self.check_function_at(function, 0)
    }

    fn check_function_at(&self, function: &FunctionType, depth: usize) -> Result<(), Error> {
        check_depth(depth)?;
        if !function.prototype {
            return Err(Error("C function declaration without a prototype cannot be represented by a Rust function signature".into()));
        }
        self.check_value(&function.return_type, &mut BTreeSet::new(), depth + 1)?;
        for parameter in &function.parameters {
            self.check_value(&parameter.ty, &mut BTreeSet::new(), depth + 1)?;
        }
        Ok(())
    }

    fn check_value(
        &self,
        ty: &Type,
        active: &mut BTreeSet<usize>,
        depth: usize,
    ) -> Result<(), Error> {
        check_depth(depth)?;
        match &self.unit.resolve(ty)?.kind {
            TypeKind::Record(id) => {
                if !active.insert(*id) {
                    return Err(Error("recursive record by value".into()));
                }
                let fields = self
                    .unit
                    .records
                    .get(*id)
                    .ok_or_else(|| Error("invalid record identity".into()))?
                    .fields
                    .as_ref()
                    .ok_or_else(|| Error("incomplete record passed by value".into()))?;
                for field in fields {
                    if field.bit_width.is_some() {
                        return Err(Error(
                            "records containing bitfields cannot yet cross an FFI call by value"
                                .into(),
                        ));
                    }
                    self.check_value(&field.ty, active, depth + 1)?;
                }
                active.remove(id);
            }
            TypeKind::Array { element, .. } => self.check_value(element, active, depth + 1)?,
            TypeKind::Float(FloatKind::LongDouble) => {
                return Err(Error("long double by value is unsupported".into()));
            }
            _ => {}
        }
        Ok(())
    }

    fn record(&self, id: usize, source: &mut String) -> Result<(), Error> {
        let record = &self.unit.records[id];
        let name = self.record_name(id)?;
        let Some(fields) = &record.fields else {
            writeln!(
                source,
                "#[repr(C)]\n#[derive(Clone, Copy)]\npub struct {name} {{ _private: [::core::primitive::u8; 0] }}\n"
            )
            .unwrap();
            return Ok(());
        };
        let layout = self.unit.layout(&Type::new(TypeKind::Record(id)))?;
        let has_bitfields = fields.iter().any(|field| field.bit_width.is_some());
        if has_bitfields && record.kind == RecordKind::Union {
            return Err(Error(format!(
                "`{name}` has union bitfields, which are not yet supported in Rust bindings"
            )));
        }
        let mut repr = vec!["C".to_owned()];
        let pack = if record.packed { Some(1) } else { record.pack };
        if pack.is_some() && record.alignment.is_some() {
            return Err(Error(format!(
                "`{name}` combines packing and explicit alignment"
            )));
        }
        if let Some(pack) = pack {
            repr.push(format!("packed({pack})"));
        }
        if let Some(alignment) = record
            .alignment
            .or_else(|| (has_bitfields && pack.is_none()).then_some(layout.alignment_bytes()))
        {
            repr.push(format!("align({alignment})"));
        }
        let kind = match record.kind {
            RecordKind::Struct => "struct",
            RecordKind::Union => "union",
        };
        writeln!(
            source,
            "#[repr({})]\n#[derive(Clone, Copy)]\npub {kind} {name} {{",
            repr.join(", ")
        )
        .unwrap();
        let mut index = 0;
        let mut byte_offset = 0;
        let mut accessors = String::new();
        let names = Names::new(fields.iter().filter_map(|field| field.name.as_deref()));
        let mut used_methods = fields
            .iter()
            .filter_map(|field| field.name.as_deref())
            .map(|name| names.identifier(name))
            .collect::<Result<BTreeSet<_>, _>>()?;
        let mut accessor_names = BTreeMap::new();
        for (index, field) in fields.iter().enumerate() {
            if field.bit_width.is_some()
                && let Some(name) = &field.name
            {
                let getter = names.identifier(name)?;
                let mut setter = format!("set_{name}");
                while !used_methods.insert(setter.clone()) {
                    setter.push('_');
                }
                accessor_names.insert(index, (getter, identifier(&setter)?));
            }
        }
        while index < fields.len() {
            let field = &fields[index];
            if field.bit_width.is_some() {
                let start_index = index;
                while index < fields.len() && fields[index].bit_width.is_some() {
                    index += 1;
                }
                let addressable: Vec<_> = (start_index..index)
                    .filter_map(|i| layout.fields[i].map(|value| (i, value)))
                    .collect();
                let mut segments: Vec<BitfieldSegment> = Vec::new();
                for (field_index, field_layout) in addressable {
                    let start = field_layout.offset_bits / 8;
                    let end = (field_layout.offset_bits + field_layout.size_bits).div_ceil(8);
                    if let Some(segment) =
                        segments.last_mut().filter(|segment| start <= segment.end)
                    {
                        segment.end = segment.end.max(end);
                        segment.fields.push((field_index, field_layout));
                    } else {
                        segments.push(BitfieldSegment {
                            start,
                            end,
                            fields: vec![(field_index, field_layout)],
                        });
                    }
                }
                for BitfieldSegment {
                    start,
                    end,
                    fields: bitfields,
                } in segments
                {
                    if start < byte_offset {
                        return Err(Error(
                            "overlapping bitfield allocation cannot be represented".into(),
                        ));
                    }
                    let first = bitfields[0].0;
                    if start > byte_offset {
                        let padding = helper_field(fields, &format!("__toucan_padding_{first}"));
                        writeln!(
                            source,
                            "    {padding}: ::core::mem::MaybeUninit<[::core::primitive::u8; {}]>,",
                            start - byte_offset
                        )
                        .unwrap();
                    }
                    let storage = helper_field(fields, &format!("__toucan_bits_{first}"));
                    writeln!(
                        source,
                        "    {storage}: [::core::primitive::u8; {}],",
                        end - start
                    )
                    .unwrap();
                    byte_offset = end;
                    for (field_index, field_layout) in bitfields {
                        let field = &fields[field_index];
                        if let Some((getter, setter)) = accessor_names.get(&field_index) {
                            self.bitfield_accessors(
                                getter,
                                setter,
                                &field.ty,
                                field_layout.offset_bits - start * 8,
                                field.bit_width.unwrap(),
                                &storage,
                                &mut accessors,
                            )?;
                        }
                    }
                }
                continue;
            }
            if field.alignment.is_some() || field.packed {
                return Err(Error(format!(
                    "`{name}` has field-level alignment or packing"
                )));
            }
            let field_name = match &field.name {
                Some(name) => names.identifier(name)?,
                None => helper_field(fields, &format!("__anonymous_{index}")),
            };
            if has_bitfields {
                let offset = layout.fields[index]
                    .ok_or_else(|| Error("ordinary field has no layout".into()))?
                    .offset_bits
                    / 8;
                if offset < byte_offset {
                    return Err(Error("overlapping fields cannot be represented".into()));
                }
                if offset > byte_offset {
                    let padding = helper_field(fields, &format!("__toucan_padding_{index}"));
                    writeln!(
                        source,
                        "    {padding}: ::core::mem::MaybeUninit<[::core::primitive::u8; {}]>,",
                        offset - byte_offset
                    )
                    .unwrap();
                }
                byte_offset = offset + self.unit.layout(&field.ty)?.size_bytes();
            }
            writeln!(source, "    pub {field_name}: {},", self.ty(&field.ty)?).unwrap();
            index += 1;
        }
        if has_bitfields && byte_offset < layout.size_bytes() {
            let padding = helper_field(fields, "__toucan_padding_tail");
            writeln!(
                source,
                "    {padding}: ::core::mem::MaybeUninit<[::core::primitive::u8; {}]>,",
                layout.size_bytes() - byte_offset
            )
            .unwrap();
        }
        if has_bitfields && pack.is_some() {
            let marker = helper_field(fields, "__toucan_alignment");
            writeln!(
                source,
                "    {marker}: [::core::primitive::u{}; 0],",
                layout.alignment_bits
            )
            .unwrap();
        }
        source.push_str("}\n");
        if !accessors.is_empty() {
            writeln!(source, "impl {name} {{\n{accessors}}}\n").unwrap();
        }
        writeln!(source, "const _: () = {{\n    assert!(::core::mem::size_of::<{name}>() == {});\n    assert!(::core::mem::align_of::<{name}>() == {});", layout.size_bits / 8, layout.alignment_bits / 8).unwrap();
        for (index, field) in fields.iter().enumerate() {
            if field.bit_width.is_some() {
                continue;
            }
            let field_name = match &field.name {
                Some(name) => names.identifier(name)?,
                None => helper_field(fields, &format!("__anonymous_{index}")),
            };
            if let Some(field_layout) = layout.fields.get(index).and_then(Option::as_ref) {
                writeln!(
                    source,
                    "    assert!(::core::mem::offset_of!({name}, {field_name}) == {});",
                    field_layout.offset_bits / 8
                )
                .unwrap();
            }
        }
        source.push_str("};\n\n");
        Ok(())
    }

    #[allow(clippy::too_many_arguments)]
    fn bitfield_accessors(
        &self,
        getter: &str,
        setter: &str,
        ty: &Type,
        offset: u64,
        width: u64,
        storage: &str,
        source: &mut String,
    ) -> Result<(), Error> {
        if !(1..=128).contains(&width) {
            return Err(Error("unsupported bitfield width".into()));
        }
        let rust_type = self.ty(ty)?;
        let kind = &self.unit.resolve(ty)?.kind;
        let signed = match kind {
            TypeKind::Integer(IntegerKind::Char) => self.unit.target.char_is_signed(),
            TypeKind::Integer(
                IntegerKind::SignedChar
                | IntegerKind::Short
                | IntegerKind::Int
                | IntegerKind::Long
                | IntegerKind::LongLong
                | IntegerKind::Int128,
            ) => true,
            TypeKind::Enum(id) => self.enum_type(*id)?.contains("::i"),
            _ => false,
        };
        writeln!(source, "    pub fn {getter}(&self) -> {rust_type} {{\n        let mut value: ::core::primitive::u128 = 0;\n        for bit in 0..{width} {{\n            let position = {offset} + bit;\n            value |= (((self.{storage}[position / 8] >> (position % 8)) & 1) as ::core::primitive::u128) << bit;\n        }}").unwrap();
        if matches!(kind, TypeKind::Bool) {
            source.push_str("        value != 0\n");
        } else if signed {
            writeln!(
                source,
                "        (((value << {}) as ::core::primitive::i128) >> {}) as {rust_type}",
                128 - width,
                128 - width
            )
            .unwrap();
        } else {
            writeln!(source, "        value as {rust_type}").unwrap();
        }
        source.push_str("    }\n");
        writeln!(source, "    pub fn {setter}(&mut self, value: {rust_type}) {{\n        let value = value as ::core::primitive::u128;\n        for bit in 0..{width} {{\n            let position = {offset} + bit;\n            let mask = 1 << (position % 8);\n            self.{storage}[position / 8] = (self.{storage}[position / 8] & !mask) | ((((value >> bit) & 1) as ::core::primitive::u8) << (position % 8));\n        }}\n    }}").unwrap();
        Ok(())
    }
}

/// Names in one Rust scope, used to avoid collisions when C names need rewriting.
struct Names {
    original: BTreeSet<String>,
}

impl Names {
    fn new<'a>(names: impl IntoIterator<Item = &'a str>) -> Self {
        Self {
            original: names.into_iter().map(str::to_owned).collect(),
        }
    }

    fn identifier(&self, name: &str) -> Result<String, Error> {
        if matches!(name, "self" | "Self" | "super" | "crate" | "_") {
            let mut candidate = format!("__toucan_{name}");
            while self.original.contains(&candidate) {
                candidate.push('_');
            }
            Ok(candidate)
        } else {
            identifier(name)
        }
    }
}

fn check_depth(depth: usize) -> Result<(), Error> {
    if depth >= 256 {
        Err(Error(
            "type nesting exceeds the binding limit of 256".into(),
        ))
    } else {
        Ok(())
    }
}

fn helper_field(fields: &[toucan_semantic::Field], stem: &str) -> String {
    let mut candidate = stem.to_owned();
    while fields
        .iter()
        .any(|field| field.name.as_ref() == Some(&candidate))
    {
        candidate.push('_');
    }
    candidate
}

fn identifier(name: &str) -> Result<String, Error> {
    if name.is_empty()
        || !name
            .bytes()
            .enumerate()
            .all(|(i, b)| b == b'_' || b.is_ascii_alphabetic() || (i > 0 && b.is_ascii_digit()))
    {
        return Err(Error(format!(
            "C name `{name}` cannot be represented as a Rust identifier"
        )));
    }
    if matches!(name, "self" | "Self" | "super" | "crate" | "_") {
        return Ok(format!("__toucan_{name}"));
    }
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "else", "enum", "extern", "false", "fn", "for", "if",
        "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
        "static", "struct", "trait", "true", "type", "unsafe", "use", "where", "while", "async",
        "await", "dyn", "abstract", "become", "box", "do", "final", "gen", "macro", "override",
        "priv", "typeof", "unsized", "virtual", "yield", "try",
    ];
    Ok(if KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_owned()
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use toucan_semantic::analyze;
    use toucan_target::Target;

    #[test]
    fn emits_transitive_types_callbacks_const_and_variadics() {
        let unit = analyze("typedef struct node { const char *name; struct node *next; } node; typedef int (*visit)(const node *, void *); int walk(node *, visit); int log_message(const char *, ...);", Target::parse("x86_64-unknown-linux-gnu").unwrap()).unwrap();
        let bindings = generate(
            &unit,
            &Options {
                allowlist: vec!["walk".into()],
            },
        )
        .unwrap();
        assert!(bindings.source.contains("pub struct node"));
        assert!(bindings.source.contains("*const ::core::ffi::c_char"));
        assert!(bindings.source.contains("Option<unsafe extern \"C\" fn"));
        assert!(!bindings.source.contains("pub fn log_message"));
    }

    #[test]
    fn rejects_unrepresentable_abi_and_old_style_prototypes() {
        let target = Target::parse("x86_64-unknown-linux-gnu").unwrap();
        for input in [
            "struct bits { unsigned x:3; }; struct bits f(void);",
            "int f();",
            "long double f(void);",
        ] {
            let unit = analyze(input, target).unwrap();
            assert!(generate(&unit, &Options::default()).is_err(), "{input}");
        }
    }

    #[test]
    fn array_statics_preserve_element_constness() {
        let unit = analyze(
            "extern const char version[]; typedef const int row[3]; extern row matrix[2]; extern int *const fixed_pointers[2]; extern const int *mutable_pointers[2]; extern int mutable_values[2];",
            Target::X86_64UnknownLinuxGnu,
        ).unwrap();
        let source = generate(&unit, &Options::default()).unwrap().source;
        for name in ["version", "matrix", "fixed_pointers"] {
            assert!(source.contains(&format!("pub static {name}:")), "{name}");
        }
        for name in ["mutable_pointers", "mutable_values"] {
            assert!(
                source.contains(&format!("pub static mut {name}:")),
                "{name}"
            );
        }
    }

    #[test]
    fn recursive_function_alias_returns_an_error() {
        let mut unit = analyze("typedef int recursive;", Target::X86_64UnknownLinuxGnu).unwrap();
        unit.typedefs.insert(
            "recursive".into(),
            Type::new(TypeKind::Function(Box::new(FunctionType {
                return_type: Type::new(TypeKind::Typedef("recursive".into())).pointer(),
                parameters: Vec::new(),
                variadic: false,
                prototype: true,
                calling_convention: toucan_semantic::CallingConvention::C,
            }))),
        );
        let error = generate(&unit, &Options::default()).unwrap_err();
        assert!(error.0.contains("type nesting"));
    }

    #[test]
    fn invalid_public_ir_returns_an_error() {
        let mut unit = analyze("int f(void);", Target::X86_64UnknownLinuxGnu).unwrap();
        unit.declarations[0].ty = Type::new(TypeKind::Record(usize::MAX));
        assert!(generate(&unit, &Options::default()).is_err());
        let mut unit = analyze("typedef int alias;", Target::X86_64UnknownLinuxGnu).unwrap();
        unit.typedefs
            .insert("alias".into(), Type::new(TypeKind::Record(usize::MAX)));
        assert!(generate(&unit, &Options::default()).is_err());
    }
}
