// Generated by Toucan for x86_64-unknown-linux-gnu.
// Do not edit.

#[cfg(not(all(target_arch = "x86_64", target_os = "linux", target_env = "gnu")))]
compile_error!("these C bindings were generated for a different target");

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_va_list_tag {
    pub gp_offset: ::core::ffi::c_uint,
    pub fp_offset: ::core::ffi::c_uint,
    pub overflow_arg_area: *mut ::core::ffi::c_void,
    pub reg_save_area: *mut ::core::ffi::c_void,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_va_list_tag>() == 24);
    assert!(::core::mem::align_of::<__toucan_va_list_tag>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_CCtx_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_DCtx_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_3 {
    pub error: size_t,
    pub lowerBound: ::core::ffi::c_int,
    pub upperBound: ::core::ffi::c_int,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_3>() == 16);
    assert!(::core::mem::align_of::<__toucan_record_3>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_inBuffer_s {
    pub src: *const ::core::ffi::c_void,
    pub size: size_t,
    pub pos: size_t,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_inBuffer_s>() == 24);
    assert!(::core::mem::align_of::<ZSTD_inBuffer_s>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_outBuffer_s {
    pub dst: *mut ::core::ffi::c_void,
    pub size: size_t,
    pub pos: size_t,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_outBuffer_s>() == 24);
    assert!(::core::mem::align_of::<ZSTD_outBuffer_s>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_CDict_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_DDict_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_CCtx_params_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_9 {
    pub offset: ::core::ffi::c_uint,
    pub litLength: ::core::ffi::c_uint,
    pub matchLength: ::core::ffi::c_uint,
    pub rep: ::core::ffi::c_uint,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_9>() == 16);
    assert!(::core::mem::align_of::<__toucan_record_9>() == 4);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_10 {
    pub windowLog: ::core::ffi::c_uint,
    pub chainLog: ::core::ffi::c_uint,
    pub hashLog: ::core::ffi::c_uint,
    pub searchLog: ::core::ffi::c_uint,
    pub minMatch: ::core::ffi::c_uint,
    pub targetLength: ::core::ffi::c_uint,
    pub strategy: ZSTD_strategy,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_10>() == 28);
    assert!(::core::mem::align_of::<__toucan_record_10>() == 4);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_11 {
    pub contentSizeFlag: ::core::ffi::c_int,
    pub checksumFlag: ::core::ffi::c_int,
    pub noDictIDFlag: ::core::ffi::c_int,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_11>() == 12);
    assert!(::core::mem::align_of::<__toucan_record_11>() == 4);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_12 {
    pub cParams: ZSTD_compressionParameters,
    pub fParams: ZSTD_frameParameters,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_12>() == 40);
    assert!(::core::mem::align_of::<__toucan_record_12>() == 4);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_13 {
    pub frameContentSize: ::core::ffi::c_ulonglong,
    pub windowSize: ::core::ffi::c_ulonglong,
    pub blockSizeMax: ::core::ffi::c_uint,
    pub frameType: ZSTD_FrameType_e,
    pub headerSize: ::core::ffi::c_uint,
    pub dictID: ::core::ffi::c_uint,
    pub checksumFlag: ::core::ffi::c_uint,
    pub _reserved1: ::core::ffi::c_uint,
    pub _reserved2: ::core::ffi::c_uint,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_13>() == 48);
    assert!(::core::mem::align_of::<__toucan_record_13>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_14 {
    pub customAlloc: ZSTD_allocFunction,
    pub customFree: ZSTD_freeFunction,
    pub opaque: *mut ::core::ffi::c_void,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_14>() == 24);
    assert!(::core::mem::align_of::<__toucan_record_14>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct POOL_ctx_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_16 {
    pub ingested: ::core::ffi::c_ulonglong,
    pub consumed: ::core::ffi::c_ulonglong,
    pub produced: ::core::ffi::c_ulonglong,
    pub flushed: ::core::ffi::c_ulonglong,
    pub currentJobID: ::core::ffi::c_uint,
    pub nbActiveWorkers: ::core::ffi::c_uint,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_16>() == 40);
    assert!(::core::mem::align_of::<__toucan_record_16>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_17 {
    pub compressionLevel: ::core::ffi::c_int,
    pub notificationLevel: ::core::ffi::c_uint,
    pub dictID: ::core::ffi::c_uint,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_17>() == 12);
    assert!(::core::mem::align_of::<__toucan_record_17>() == 4);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_18 {
    pub k: ::core::ffi::c_uint,
    pub d: ::core::ffi::c_uint,
    pub steps: ::core::ffi::c_uint,
    pub nbThreads: ::core::ffi::c_uint,
    pub splitPoint: ::core::primitive::f64,
    pub shrinkDict: ::core::ffi::c_uint,
    pub shrinkDictMaxRegression: ::core::ffi::c_uint,
    pub zParams: ZDICT_params_t,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_18>() == 48);
    assert!(::core::mem::align_of::<__toucan_record_18>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_19 {
    pub k: ::core::ffi::c_uint,
    pub d: ::core::ffi::c_uint,
    pub f: ::core::ffi::c_uint,
    pub steps: ::core::ffi::c_uint,
    pub nbThreads: ::core::ffi::c_uint,
    pub splitPoint: ::core::primitive::f64,
    pub accel: ::core::ffi::c_uint,
    pub shrinkDict: ::core::ffi::c_uint,
    pub shrinkDictMaxRegression: ::core::ffi::c_uint,
    pub zParams: ZDICT_params_t,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_19>() == 56);
    assert!(::core::mem::align_of::<__toucan_record_19>() == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_20 {
    pub selectivityLevel: ::core::ffi::c_uint,
    pub zParams: ZDICT_params_t,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_20>() == 16);
    assert!(::core::mem::align_of::<__toucan_record_20>() == 4);
};

#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_ErrorCode {
    ZSTD_error_no_error = 0,
    ZSTD_error_GENERIC = 1,
    ZSTD_error_prefix_unknown = 10,
    ZSTD_error_version_unsupported = 12,
    ZSTD_error_frameParameter_unsupported = 14,
    ZSTD_error_frameParameter_windowTooLarge = 16,
    ZSTD_error_corruption_detected = 20,
    ZSTD_error_checksum_wrong = 22,
    ZSTD_error_literals_headerWrong = 24,
    ZSTD_error_dictionary_corrupted = 30,
    ZSTD_error_dictionary_wrong = 32,
    ZSTD_error_dictionaryCreation_failed = 34,
    ZSTD_error_parameter_unsupported = 40,
    ZSTD_error_parameter_combination_unsupported = 41,
    ZSTD_error_parameter_outOfBound = 42,
    ZSTD_error_tableLog_tooLarge = 44,
    ZSTD_error_maxSymbolValue_tooLarge = 46,
    ZSTD_error_maxSymbolValue_tooSmall = 48,
    ZSTD_error_cannotProduce_uncompressedBlock = 49,
    ZSTD_error_stabilityCondition_notRespected = 50,
    ZSTD_error_stage_wrong = 60,
    ZSTD_error_init_missing = 62,
    ZSTD_error_memory_allocation = 64,
    ZSTD_error_workSpace_tooSmall = 66,
    ZSTD_error_dstSize_tooSmall = 70,
    ZSTD_error_srcSize_wrong = 72,
    ZSTD_error_dstBuffer_null = 74,
    ZSTD_error_noForwardProgress_destFull = 80,
    ZSTD_error_noForwardProgress_inputEmpty = 82,
    ZSTD_error_frameIndex_tooLarge = 100,
    ZSTD_error_seekableIO = 102,
    ZSTD_error_dstBuffer_wrong = 104,
    ZSTD_error_srcBuffer_wrong = 105,
    ZSTD_error_sequenceProducer_failed = 106,
    ZSTD_error_externalSequences_invalid = 107,
    ZSTD_error_maxCode = 120,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_ErrorCode>() == 4);
    assert!(::core::mem::align_of::<ZSTD_ErrorCode>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_strategy {
    ZSTD_fast = 1,
    ZSTD_dfast = 2,
    ZSTD_greedy = 3,
    ZSTD_lazy = 4,
    ZSTD_lazy2 = 5,
    ZSTD_btlazy2 = 6,
    ZSTD_btopt = 7,
    ZSTD_btultra = 8,
    ZSTD_btultra2 = 9,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_strategy>() == 4);
    assert!(::core::mem::align_of::<ZSTD_strategy>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_cParameter {
    ZSTD_c_compressionLevel = 100,
    ZSTD_c_windowLog = 101,
    ZSTD_c_hashLog = 102,
    ZSTD_c_chainLog = 103,
    ZSTD_c_searchLog = 104,
    ZSTD_c_minMatch = 105,
    ZSTD_c_targetLength = 106,
    ZSTD_c_strategy = 107,
    ZSTD_c_targetCBlockSize = 130,
    ZSTD_c_enableLongDistanceMatching = 160,
    ZSTD_c_ldmHashLog = 161,
    ZSTD_c_ldmMinMatch = 162,
    ZSTD_c_ldmBucketSizeLog = 163,
    ZSTD_c_ldmHashRateLog = 164,
    ZSTD_c_contentSizeFlag = 200,
    ZSTD_c_checksumFlag = 201,
    ZSTD_c_dictIDFlag = 202,
    ZSTD_c_nbWorkers = 400,
    ZSTD_c_jobSize = 401,
    ZSTD_c_overlapLog = 402,
    ZSTD_c_experimentalParam1 = 500,
    ZSTD_c_experimentalParam2 = 10,
    ZSTD_c_experimentalParam3 = 1000,
    ZSTD_c_experimentalParam4 = 1001,
    ZSTD_c_experimentalParam5 = 1002,
    ZSTD_c_experimentalParam7 = 1004,
    ZSTD_c_experimentalParam8 = 1005,
    ZSTD_c_experimentalParam9 = 1006,
    ZSTD_c_experimentalParam10 = 1007,
    ZSTD_c_experimentalParam11 = 1008,
    ZSTD_c_experimentalParam12 = 1009,
    ZSTD_c_experimentalParam13 = 1010,
    ZSTD_c_experimentalParam14 = 1011,
    ZSTD_c_experimentalParam15 = 1012,
    ZSTD_c_experimentalParam16 = 1013,
    ZSTD_c_experimentalParam17 = 1014,
    ZSTD_c_experimentalParam18 = 1015,
    ZSTD_c_experimentalParam19 = 1016,
    ZSTD_c_experimentalParam20 = 1017,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_cParameter>() == 4);
    assert!(::core::mem::align_of::<ZSTD_cParameter>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_ResetDirective {
    ZSTD_reset_session_only = 1,
    ZSTD_reset_parameters = 2,
    ZSTD_reset_session_and_parameters = 3,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_ResetDirective>() == 4);
    assert!(::core::mem::align_of::<ZSTD_ResetDirective>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_dParameter {
    ZSTD_d_windowLogMax = 100,
    ZSTD_d_experimentalParam1 = 1000,
    ZSTD_d_experimentalParam2 = 1001,
    ZSTD_d_experimentalParam3 = 1002,
    ZSTD_d_experimentalParam4 = 1003,
    ZSTD_d_experimentalParam5 = 1004,
    ZSTD_d_experimentalParam6 = 1005,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_dParameter>() == 4);
    assert!(::core::mem::align_of::<ZSTD_dParameter>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_EndDirective {
    ZSTD_e_continue = 0,
    ZSTD_e_flush = 1,
    ZSTD_e_end = 2,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_EndDirective>() == 4);
    assert!(::core::mem::align_of::<ZSTD_EndDirective>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_dictContentType_e {
    ZSTD_dct_auto = 0,
    ZSTD_dct_rawContent = 1,
    ZSTD_dct_fullDict = 2,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_dictContentType_e>() == 4);
    assert!(::core::mem::align_of::<ZSTD_dictContentType_e>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_dictLoadMethod_e {
    ZSTD_dlm_byCopy = 0,
    ZSTD_dlm_byRef = 1,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_dictLoadMethod_e>() == 4);
    assert!(::core::mem::align_of::<ZSTD_dictLoadMethod_e>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_format_e {
    ZSTD_f_zstd1 = 0,
    ZSTD_f_zstd1_magicless = 1,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_format_e>() == 4);
    assert!(::core::mem::align_of::<ZSTD_format_e>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_forceIgnoreChecksum_e {
    ZSTD_d_validateChecksum = 0,
    ZSTD_d_ignoreChecksum = 1,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_forceIgnoreChecksum_e>() == 4);
    assert!(::core::mem::align_of::<ZSTD_forceIgnoreChecksum_e>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_refMultipleDDicts_e {
    ZSTD_rmd_refSingleDDict = 0,
    ZSTD_rmd_refMultipleDDicts = 1,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_refMultipleDDicts_e>() == 4);
    assert!(::core::mem::align_of::<ZSTD_refMultipleDDicts_e>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_dictAttachPref_e {
    ZSTD_dictDefaultAttach = 0,
    ZSTD_dictForceAttach = 1,
    ZSTD_dictForceCopy = 2,
    ZSTD_dictForceLoad = 3,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_dictAttachPref_e>() == 4);
    assert!(::core::mem::align_of::<ZSTD_dictAttachPref_e>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_literalCompressionMode_e {
    ZSTD_lcm_auto = 0,
    ZSTD_lcm_huffman = 1,
    ZSTD_lcm_uncompressed = 2,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_literalCompressionMode_e>() == 4);
    assert!(::core::mem::align_of::<ZSTD_literalCompressionMode_e>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_ParamSwitch_e {
    ZSTD_ps_auto = 0,
    ZSTD_ps_enable = 1,
    ZSTD_ps_disable = 2,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_ParamSwitch_e>() == 4);
    assert!(::core::mem::align_of::<ZSTD_ParamSwitch_e>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_FrameType_e {
    ZSTD_frame = 0,
    ZSTD_skippableFrame = 1,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_FrameType_e>() == 4);
    assert!(::core::mem::align_of::<ZSTD_FrameType_e>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_SequenceFormat_e {
    ZSTD_sf_noBlockDelimiters = 0,
    ZSTD_sf_explicitBlockDelimiters = 1,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_SequenceFormat_e>() == 4);
    assert!(::core::mem::align_of::<ZSTD_SequenceFormat_e>() == 4);
};
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZSTD_nextInputType_e {
    ZSTDnit_frameHeader = 0,
    ZSTDnit_blockHeader = 1,
    ZSTDnit_block = 2,
    ZSTDnit_lastBlock = 3,
    ZSTDnit_checksum = 4,
    ZSTDnit_skippableFrame = 5,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_nextInputType_e>() == 4);
    assert!(::core::mem::align_of::<ZSTD_nextInputType_e>() == 4);
};
pub type ZDICT_cover_params_t = __toucan_record_18;
pub type ZDICT_fastCover_params_t = __toucan_record_19;
pub type ZDICT_legacy_params_t = __toucan_record_20;
pub type ZDICT_params_t = __toucan_record_17;
pub type ZSTD_CCtx = ZSTD_CCtx_s;
pub type ZSTD_CCtx_params = ZSTD_CCtx_params_s;
pub type ZSTD_CDict = ZSTD_CDict_s;
pub type ZSTD_CStream = ZSTD_CCtx;
pub type ZSTD_DCtx = ZSTD_DCtx_s;
pub type ZSTD_DDict = ZSTD_DDict_s;
pub type ZSTD_DStream = ZSTD_DCtx;
pub type ZSTD_FrameHeader = __toucan_record_13;
pub type ZSTD_Sequence = __toucan_record_9;
pub type ZSTD_allocFunction = ::core::option::Option<unsafe extern "C" fn(arg0: *mut ::core::ffi::c_void, arg1: size_t) -> *mut ::core::ffi::c_void>;
pub type ZSTD_bounds = __toucan_record_3;
pub type ZSTD_compressionParameters = __toucan_record_10;
pub type ZSTD_customMem = __toucan_record_14;
pub type ZSTD_frameParameters = __toucan_record_11;
pub type ZSTD_frameProgression = __toucan_record_16;
pub type ZSTD_freeFunction = ::core::option::Option<unsafe extern "C" fn(arg0: *mut ::core::ffi::c_void, arg1: *mut ::core::ffi::c_void)>;
pub type ZSTD_inBuffer = ZSTD_inBuffer_s;
pub type ZSTD_outBuffer = ZSTD_outBuffer_s;
pub type ZSTD_parameters = __toucan_record_12;
pub type ZSTD_sequenceProducer_F = ::core::option::Option<unsafe extern "C" fn(arg0: *mut ::core::ffi::c_void, arg1: *mut ZSTD_Sequence, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ::core::ffi::c_void, arg6: size_t, arg7: ::core::ffi::c_int, arg8: size_t) -> size_t>;
pub type ZSTD_threadPool = POOL_ctx_s;
pub type ptrdiff_t = ::core::ffi::c_long;
pub type size_t = ::core::primitive::usize;
pub type wchar_t = ::core::ffi::c_int;
pub const ZSTD_btlazy2: ::core::primitive::u32 = 6;
pub const ZSTD_btopt: ::core::primitive::u32 = 7;
pub const ZSTD_btultra: ::core::primitive::u32 = 8;
pub const ZSTD_btultra2: ::core::primitive::u32 = 9;
pub const ZSTD_c_chainLog: ::core::primitive::u32 = 103;
pub const ZSTD_c_checksumFlag: ::core::primitive::u32 = 201;
pub const ZSTD_c_compressionLevel: ::core::primitive::u32 = 100;
pub const ZSTD_c_contentSizeFlag: ::core::primitive::u32 = 200;
pub const ZSTD_c_dictIDFlag: ::core::primitive::u32 = 202;
pub const ZSTD_c_enableLongDistanceMatching: ::core::primitive::u32 = 160;
pub const ZSTD_c_experimentalParam1: ::core::primitive::u32 = 500;
pub const ZSTD_c_experimentalParam10: ::core::primitive::u32 = 1007;
pub const ZSTD_c_experimentalParam11: ::core::primitive::u32 = 1008;
pub const ZSTD_c_experimentalParam12: ::core::primitive::u32 = 1009;
pub const ZSTD_c_experimentalParam13: ::core::primitive::u32 = 1010;
pub const ZSTD_c_experimentalParam14: ::core::primitive::u32 = 1011;
pub const ZSTD_c_experimentalParam15: ::core::primitive::u32 = 1012;
pub const ZSTD_c_experimentalParam16: ::core::primitive::u32 = 1013;
pub const ZSTD_c_experimentalParam17: ::core::primitive::u32 = 1014;
pub const ZSTD_c_experimentalParam18: ::core::primitive::u32 = 1015;
pub const ZSTD_c_experimentalParam19: ::core::primitive::u32 = 1016;
pub const ZSTD_c_experimentalParam2: ::core::primitive::u32 = 10;
pub const ZSTD_c_experimentalParam20: ::core::primitive::u32 = 1017;
pub const ZSTD_c_experimentalParam3: ::core::primitive::u32 = 1000;
pub const ZSTD_c_experimentalParam4: ::core::primitive::u32 = 1001;
pub const ZSTD_c_experimentalParam5: ::core::primitive::u32 = 1002;
pub const ZSTD_c_experimentalParam7: ::core::primitive::u32 = 1004;
pub const ZSTD_c_experimentalParam8: ::core::primitive::u32 = 1005;
pub const ZSTD_c_experimentalParam9: ::core::primitive::u32 = 1006;
pub const ZSTD_c_hashLog: ::core::primitive::u32 = 102;
pub const ZSTD_c_jobSize: ::core::primitive::u32 = 401;
pub const ZSTD_c_ldmBucketSizeLog: ::core::primitive::u32 = 163;
pub const ZSTD_c_ldmHashLog: ::core::primitive::u32 = 161;
pub const ZSTD_c_ldmHashRateLog: ::core::primitive::u32 = 164;
pub const ZSTD_c_ldmMinMatch: ::core::primitive::u32 = 162;
pub const ZSTD_c_minMatch: ::core::primitive::u32 = 105;
pub const ZSTD_c_nbWorkers: ::core::primitive::u32 = 400;
pub const ZSTD_c_overlapLog: ::core::primitive::u32 = 402;
pub const ZSTD_c_searchLog: ::core::primitive::u32 = 104;
pub const ZSTD_c_strategy: ::core::primitive::u32 = 107;
pub const ZSTD_c_targetCBlockSize: ::core::primitive::u32 = 130;
pub const ZSTD_c_targetLength: ::core::primitive::u32 = 106;
pub const ZSTD_c_windowLog: ::core::primitive::u32 = 101;
pub const ZSTD_d_experimentalParam1: ::core::primitive::u32 = 1000;
pub const ZSTD_d_experimentalParam2: ::core::primitive::u32 = 1001;
pub const ZSTD_d_experimentalParam3: ::core::primitive::u32 = 1002;
pub const ZSTD_d_experimentalParam4: ::core::primitive::u32 = 1003;
pub const ZSTD_d_experimentalParam5: ::core::primitive::u32 = 1004;
pub const ZSTD_d_experimentalParam6: ::core::primitive::u32 = 1005;
pub const ZSTD_d_ignoreChecksum: ::core::primitive::u32 = 1;
pub const ZSTD_d_validateChecksum: ::core::primitive::u32 = 0;
pub const ZSTD_d_windowLogMax: ::core::primitive::u32 = 100;
pub const ZSTD_dct_auto: ::core::primitive::u32 = 0;
pub const ZSTD_dct_fullDict: ::core::primitive::u32 = 2;
pub const ZSTD_dct_rawContent: ::core::primitive::u32 = 1;
pub const ZSTD_dfast: ::core::primitive::u32 = 2;
pub const ZSTD_dictDefaultAttach: ::core::primitive::u32 = 0;
pub const ZSTD_dictForceAttach: ::core::primitive::u32 = 1;
pub const ZSTD_dictForceCopy: ::core::primitive::u32 = 2;
pub const ZSTD_dictForceLoad: ::core::primitive::u32 = 3;
pub const ZSTD_dlm_byCopy: ::core::primitive::u32 = 0;
pub const ZSTD_dlm_byRef: ::core::primitive::u32 = 1;
pub const ZSTD_e_continue: ::core::primitive::u32 = 0;
pub const ZSTD_e_end: ::core::primitive::u32 = 2;
pub const ZSTD_e_flush: ::core::primitive::u32 = 1;
pub const ZSTD_error_GENERIC: ::core::primitive::u32 = 1;
pub const ZSTD_error_cannotProduce_uncompressedBlock: ::core::primitive::u32 = 49;
pub const ZSTD_error_checksum_wrong: ::core::primitive::u32 = 22;
pub const ZSTD_error_corruption_detected: ::core::primitive::u32 = 20;
pub const ZSTD_error_dictionaryCreation_failed: ::core::primitive::u32 = 34;
pub const ZSTD_error_dictionary_corrupted: ::core::primitive::u32 = 30;
pub const ZSTD_error_dictionary_wrong: ::core::primitive::u32 = 32;
pub const ZSTD_error_dstBuffer_null: ::core::primitive::u32 = 74;
pub const ZSTD_error_dstBuffer_wrong: ::core::primitive::u32 = 104;
pub const ZSTD_error_dstSize_tooSmall: ::core::primitive::u32 = 70;
pub const ZSTD_error_externalSequences_invalid: ::core::primitive::u32 = 107;
pub const ZSTD_error_frameIndex_tooLarge: ::core::primitive::u32 = 100;
pub const ZSTD_error_frameParameter_unsupported: ::core::primitive::u32 = 14;
pub const ZSTD_error_frameParameter_windowTooLarge: ::core::primitive::u32 = 16;
pub const ZSTD_error_init_missing: ::core::primitive::u32 = 62;
pub const ZSTD_error_literals_headerWrong: ::core::primitive::u32 = 24;
pub const ZSTD_error_maxCode: ::core::primitive::u32 = 120;
pub const ZSTD_error_maxSymbolValue_tooLarge: ::core::primitive::u32 = 46;
pub const ZSTD_error_maxSymbolValue_tooSmall: ::core::primitive::u32 = 48;
pub const ZSTD_error_memory_allocation: ::core::primitive::u32 = 64;
pub const ZSTD_error_noForwardProgress_destFull: ::core::primitive::u32 = 80;
pub const ZSTD_error_noForwardProgress_inputEmpty: ::core::primitive::u32 = 82;
pub const ZSTD_error_no_error: ::core::primitive::u32 = 0;
pub const ZSTD_error_parameter_combination_unsupported: ::core::primitive::u32 = 41;
pub const ZSTD_error_parameter_outOfBound: ::core::primitive::u32 = 42;
pub const ZSTD_error_parameter_unsupported: ::core::primitive::u32 = 40;
pub const ZSTD_error_prefix_unknown: ::core::primitive::u32 = 10;
pub const ZSTD_error_seekableIO: ::core::primitive::u32 = 102;
pub const ZSTD_error_sequenceProducer_failed: ::core::primitive::u32 = 106;
pub const ZSTD_error_srcBuffer_wrong: ::core::primitive::u32 = 105;
pub const ZSTD_error_srcSize_wrong: ::core::primitive::u32 = 72;
pub const ZSTD_error_stabilityCondition_notRespected: ::core::primitive::u32 = 50;
pub const ZSTD_error_stage_wrong: ::core::primitive::u32 = 60;
pub const ZSTD_error_tableLog_tooLarge: ::core::primitive::u32 = 44;
pub const ZSTD_error_version_unsupported: ::core::primitive::u32 = 12;
pub const ZSTD_error_workSpace_tooSmall: ::core::primitive::u32 = 66;
pub const ZSTD_f_zstd1: ::core::primitive::u32 = 0;
pub const ZSTD_f_zstd1_magicless: ::core::primitive::u32 = 1;
pub const ZSTD_fast: ::core::primitive::u32 = 1;
pub const ZSTD_frame: ::core::primitive::u32 = 0;
pub const ZSTD_greedy: ::core::primitive::u32 = 3;
pub const ZSTD_lazy: ::core::primitive::u32 = 4;
pub const ZSTD_lazy2: ::core::primitive::u32 = 5;
pub const ZSTD_lcm_auto: ::core::primitive::u32 = 0;
pub const ZSTD_lcm_huffman: ::core::primitive::u32 = 1;
pub const ZSTD_lcm_uncompressed: ::core::primitive::u32 = 2;
pub const ZSTD_ps_auto: ::core::primitive::u32 = 0;
pub const ZSTD_ps_disable: ::core::primitive::u32 = 2;
pub const ZSTD_ps_enable: ::core::primitive::u32 = 1;
pub const ZSTD_reset_parameters: ::core::primitive::u32 = 2;
pub const ZSTD_reset_session_and_parameters: ::core::primitive::u32 = 3;
pub const ZSTD_reset_session_only: ::core::primitive::u32 = 1;
pub const ZSTD_rmd_refMultipleDDicts: ::core::primitive::u32 = 1;
pub const ZSTD_rmd_refSingleDDict: ::core::primitive::u32 = 0;
pub const ZSTD_sf_explicitBlockDelimiters: ::core::primitive::u32 = 1;
pub const ZSTD_sf_noBlockDelimiters: ::core::primitive::u32 = 0;
pub const ZSTD_skippableFrame: ::core::primitive::u32 = 1;
pub const ZSTDnit_block: ::core::primitive::u32 = 2;
pub const ZSTDnit_blockHeader: ::core::primitive::u32 = 1;
pub const ZSTDnit_checksum: ::core::primitive::u32 = 4;
pub const ZSTDnit_frameHeader: ::core::primitive::u32 = 0;
pub const ZSTDnit_lastBlock: ::core::primitive::u32 = 3;
pub const ZSTDnit_skippableFrame: ::core::primitive::u32 = 5;

extern "C" {
    pub fn ZSTD_getErrorString(arg0: ZSTD_ErrorCode) -> *const ::core::ffi::c_char;
    pub fn ZSTD_versionNumber() -> ::core::ffi::c_uint;
    pub fn ZSTD_versionString() -> *const ::core::ffi::c_char;
    pub fn ZSTD_compress(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: size_t, arg4: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_decompress(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: size_t) -> size_t;
    pub fn ZSTD_getFrameContentSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_ulonglong;
    pub fn ZSTD_getDecompressedSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_ulonglong;
    pub fn ZSTD_findFrameCompressedSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> size_t;
    pub fn ZSTD_compressBound(arg0: size_t) -> size_t;
    pub fn ZSTD_isError(arg0: size_t) -> ::core::ffi::c_uint;
    pub fn ZSTD_getErrorCode(arg0: size_t) -> ZSTD_ErrorCode;
    pub fn ZSTD_getErrorName(arg0: size_t) -> *const ::core::ffi::c_char;
    pub fn ZSTD_minCLevel() -> ::core::ffi::c_int;
    pub fn ZSTD_maxCLevel() -> ::core::ffi::c_int;
    pub fn ZSTD_defaultCLevel() -> ::core::ffi::c_int;
    pub fn ZSTD_createCCtx() -> *mut ZSTD_CCtx;
    pub fn ZSTD_freeCCtx(arg0: *mut ZSTD_CCtx) -> size_t;
    pub fn ZSTD_compressCCtx(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_createDCtx() -> *mut ZSTD_DCtx;
    pub fn ZSTD_freeDCtx(arg0: *mut ZSTD_DCtx) -> size_t;
    pub fn ZSTD_decompressDCtx(arg0: *mut ZSTD_DCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_cParam_getBounds(arg0: ZSTD_cParameter) -> ZSTD_bounds;
    pub fn ZSTD_CCtx_setParameter(arg0: *mut ZSTD_CCtx, arg1: ZSTD_cParameter, arg2: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_CCtx_setPledgedSrcSize(arg0: *mut ZSTD_CCtx, arg1: ::core::ffi::c_ulonglong) -> size_t;
    pub fn ZSTD_CCtx_reset(arg0: *mut ZSTD_CCtx, arg1: ZSTD_ResetDirective) -> size_t;
    pub fn ZSTD_compress2(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_dParam_getBounds(arg0: ZSTD_dParameter) -> ZSTD_bounds;
    pub fn ZSTD_DCtx_setParameter(arg0: *mut ZSTD_DCtx, arg1: ZSTD_dParameter, arg2: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_DCtx_reset(arg0: *mut ZSTD_DCtx, arg1: ZSTD_ResetDirective) -> size_t;
    pub fn ZSTD_createCStream() -> *mut ZSTD_CStream;
    pub fn ZSTD_freeCStream(arg0: *mut ZSTD_CStream) -> size_t;
    pub fn ZSTD_compressStream2(arg0: *mut ZSTD_CCtx, arg1: *mut ZSTD_outBuffer, arg2: *mut ZSTD_inBuffer, arg3: ZSTD_EndDirective) -> size_t;
    pub fn ZSTD_CStreamInSize() -> size_t;
    pub fn ZSTD_CStreamOutSize() -> size_t;
    pub fn ZSTD_initCStream(arg0: *mut ZSTD_CStream, arg1: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_compressStream(arg0: *mut ZSTD_CStream, arg1: *mut ZSTD_outBuffer, arg2: *mut ZSTD_inBuffer) -> size_t;
    pub fn ZSTD_flushStream(arg0: *mut ZSTD_CStream, arg1: *mut ZSTD_outBuffer) -> size_t;
    pub fn ZSTD_endStream(arg0: *mut ZSTD_CStream, arg1: *mut ZSTD_outBuffer) -> size_t;
    pub fn ZSTD_createDStream() -> *mut ZSTD_DStream;
    pub fn ZSTD_freeDStream(arg0: *mut ZSTD_DStream) -> size_t;
    pub fn ZSTD_initDStream(arg0: *mut ZSTD_DStream) -> size_t;
    pub fn ZSTD_decompressStream(arg0: *mut ZSTD_DStream, arg1: *mut ZSTD_outBuffer, arg2: *mut ZSTD_inBuffer) -> size_t;
    pub fn ZSTD_DStreamInSize() -> size_t;
    pub fn ZSTD_DStreamOutSize() -> size_t;
    pub fn ZSTD_compress_usingDict(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ::core::ffi::c_void, arg6: size_t, arg7: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_decompress_usingDict(arg0: *mut ZSTD_DCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ::core::ffi::c_void, arg6: size_t) -> size_t;
    pub fn ZSTD_createCDict(arg0: *const ::core::ffi::c_void, arg1: size_t, arg2: ::core::ffi::c_int) -> *mut ZSTD_CDict;
    pub fn ZSTD_freeCDict(arg0: *mut ZSTD_CDict) -> size_t;
    pub fn ZSTD_compress_usingCDict(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ZSTD_CDict) -> size_t;
    pub fn ZSTD_createDDict(arg0: *const ::core::ffi::c_void, arg1: size_t) -> *mut ZSTD_DDict;
    pub fn ZSTD_freeDDict(arg0: *mut ZSTD_DDict) -> size_t;
    pub fn ZSTD_decompress_usingDDict(arg0: *mut ZSTD_DCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ZSTD_DDict) -> size_t;
    pub fn ZSTD_getDictID_fromDict(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_uint;
    pub fn ZSTD_getDictID_fromCDict(arg0: *const ZSTD_CDict) -> ::core::ffi::c_uint;
    pub fn ZSTD_getDictID_fromDDict(arg0: *const ZSTD_DDict) -> ::core::ffi::c_uint;
    pub fn ZSTD_getDictID_fromFrame(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_uint;
    pub fn ZSTD_CCtx_loadDictionary(arg0: *mut ZSTD_CCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_CCtx_refCDict(arg0: *mut ZSTD_CCtx, arg1: *const ZSTD_CDict) -> size_t;
    pub fn ZSTD_CCtx_refPrefix(arg0: *mut ZSTD_CCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_DCtx_loadDictionary(arg0: *mut ZSTD_DCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_DCtx_refDDict(arg0: *mut ZSTD_DCtx, arg1: *const ZSTD_DDict) -> size_t;
    pub fn ZSTD_DCtx_refPrefix(arg0: *mut ZSTD_DCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_sizeof_CCtx(arg0: *const ZSTD_CCtx) -> size_t;
    pub fn ZSTD_sizeof_DCtx(arg0: *const ZSTD_DCtx) -> size_t;
    pub fn ZSTD_sizeof_CStream(arg0: *const ZSTD_CStream) -> size_t;
    pub fn ZSTD_sizeof_DStream(arg0: *const ZSTD_DStream) -> size_t;
    pub fn ZSTD_sizeof_CDict(arg0: *const ZSTD_CDict) -> size_t;
    pub fn ZSTD_sizeof_DDict(arg0: *const ZSTD_DDict) -> size_t;
    pub fn ZSTD_findDecompressedSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_ulonglong;
    pub fn ZSTD_decompressBound(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_ulonglong;
    pub fn ZSTD_frameHeaderSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> size_t;
    pub fn ZSTD_getFrameHeader(arg0: *mut ZSTD_FrameHeader, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_getFrameHeader_advanced(arg0: *mut ZSTD_FrameHeader, arg1: *const ::core::ffi::c_void, arg2: size_t, arg3: ZSTD_format_e) -> size_t;
    pub fn ZSTD_decompressionMargin(arg0: *const ::core::ffi::c_void, arg1: size_t) -> size_t;
    pub fn ZSTD_sequenceBound(arg0: size_t) -> size_t;
    pub fn ZSTD_generateSequences(arg0: *mut ZSTD_CCtx, arg1: *mut ZSTD_Sequence, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_mergeBlockDelimiters(arg0: *mut ZSTD_Sequence, arg1: size_t) -> size_t;
    pub fn ZSTD_compressSequences(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ZSTD_Sequence, arg4: size_t, arg5: *const ::core::ffi::c_void, arg6: size_t) -> size_t;
    pub fn ZSTD_compressSequencesAndLiterals(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ZSTD_Sequence, arg4: size_t, arg5: *const ::core::ffi::c_void, arg6: size_t, arg7: size_t, arg8: size_t) -> size_t;
    pub fn ZSTD_writeSkippableFrame(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: size_t, arg4: ::core::ffi::c_uint) -> size_t;
    pub fn ZSTD_readSkippableFrame(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *mut ::core::ffi::c_uint, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_isSkippableFrame(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_uint;
    pub fn ZSTD_estimateCCtxSize(arg0: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_estimateCCtxSize_usingCParams(arg0: ZSTD_compressionParameters) -> size_t;
    pub fn ZSTD_estimateCCtxSize_usingCCtxParams(arg0: *const ZSTD_CCtx_params) -> size_t;
    pub fn ZSTD_estimateDCtxSize() -> size_t;
    pub fn ZSTD_estimateCStreamSize(arg0: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_estimateCStreamSize_usingCParams(arg0: ZSTD_compressionParameters) -> size_t;
    pub fn ZSTD_estimateCStreamSize_usingCCtxParams(arg0: *const ZSTD_CCtx_params) -> size_t;
    pub fn ZSTD_estimateDStreamSize(arg0: size_t) -> size_t;
    pub fn ZSTD_estimateDStreamSize_fromFrame(arg0: *const ::core::ffi::c_void, arg1: size_t) -> size_t;
    pub fn ZSTD_estimateCDictSize(arg0: size_t, arg1: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_estimateCDictSize_advanced(arg0: size_t, arg1: ZSTD_compressionParameters, arg2: ZSTD_dictLoadMethod_e) -> size_t;
    pub fn ZSTD_estimateDDictSize(arg0: size_t, arg1: ZSTD_dictLoadMethod_e) -> size_t;
    pub fn ZSTD_initStaticCCtx(arg0: *mut ::core::ffi::c_void, arg1: size_t) -> *mut ZSTD_CCtx;
    pub fn ZSTD_initStaticCStream(arg0: *mut ::core::ffi::c_void, arg1: size_t) -> *mut ZSTD_CStream;
    pub fn ZSTD_initStaticDCtx(arg0: *mut ::core::ffi::c_void, arg1: size_t) -> *mut ZSTD_DCtx;
    pub fn ZSTD_initStaticDStream(arg0: *mut ::core::ffi::c_void, arg1: size_t) -> *mut ZSTD_DStream;
    pub fn ZSTD_initStaticCDict(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: size_t, arg4: ZSTD_dictLoadMethod_e, arg5: ZSTD_dictContentType_e, arg6: ZSTD_compressionParameters) -> *const ZSTD_CDict;
    pub fn ZSTD_initStaticDDict(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: size_t, arg4: ZSTD_dictLoadMethod_e, arg5: ZSTD_dictContentType_e) -> *const ZSTD_DDict;
    pub fn ZSTD_createCCtx_advanced(arg0: ZSTD_customMem) -> *mut ZSTD_CCtx;
    pub fn ZSTD_createCStream_advanced(arg0: ZSTD_customMem) -> *mut ZSTD_CStream;
    pub fn ZSTD_createDCtx_advanced(arg0: ZSTD_customMem) -> *mut ZSTD_DCtx;
    pub fn ZSTD_createDStream_advanced(arg0: ZSTD_customMem) -> *mut ZSTD_DStream;
    pub fn ZSTD_createCDict_advanced(arg0: *const ::core::ffi::c_void, arg1: size_t, arg2: ZSTD_dictLoadMethod_e, arg3: ZSTD_dictContentType_e, arg4: ZSTD_compressionParameters, arg5: ZSTD_customMem) -> *mut ZSTD_CDict;
    pub fn ZSTD_createThreadPool(arg0: size_t) -> *mut ZSTD_threadPool;
    pub fn ZSTD_freeThreadPool(arg0: *mut ZSTD_threadPool);
    pub fn ZSTD_CCtx_refThreadPool(arg0: *mut ZSTD_CCtx, arg1: *mut ZSTD_threadPool) -> size_t;
    pub fn ZSTD_createCDict_advanced2(arg0: *const ::core::ffi::c_void, arg1: size_t, arg2: ZSTD_dictLoadMethod_e, arg3: ZSTD_dictContentType_e, arg4: *const ZSTD_CCtx_params, arg5: ZSTD_customMem) -> *mut ZSTD_CDict;
    pub fn ZSTD_createDDict_advanced(arg0: *const ::core::ffi::c_void, arg1: size_t, arg2: ZSTD_dictLoadMethod_e, arg3: ZSTD_dictContentType_e, arg4: ZSTD_customMem) -> *mut ZSTD_DDict;
    pub fn ZSTD_createCDict_byReference(arg0: *const ::core::ffi::c_void, arg1: size_t, arg2: ::core::ffi::c_int) -> *mut ZSTD_CDict;
    pub fn ZSTD_getCParams(arg0: ::core::ffi::c_int, arg1: ::core::ffi::c_ulonglong, arg2: size_t) -> ZSTD_compressionParameters;
    pub fn ZSTD_getParams(arg0: ::core::ffi::c_int, arg1: ::core::ffi::c_ulonglong, arg2: size_t) -> ZSTD_parameters;
    pub fn ZSTD_checkCParams(arg0: ZSTD_compressionParameters) -> size_t;
    pub fn ZSTD_adjustCParams(arg0: ZSTD_compressionParameters, arg1: ::core::ffi::c_ulonglong, arg2: size_t) -> ZSTD_compressionParameters;
    pub fn ZSTD_CCtx_setCParams(arg0: *mut ZSTD_CCtx, arg1: ZSTD_compressionParameters) -> size_t;
    pub fn ZSTD_CCtx_setFParams(arg0: *mut ZSTD_CCtx, arg1: ZSTD_frameParameters) -> size_t;
    pub fn ZSTD_CCtx_setParams(arg0: *mut ZSTD_CCtx, arg1: ZSTD_parameters) -> size_t;
    pub fn ZSTD_compress_advanced(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ::core::ffi::c_void, arg6: size_t, arg7: ZSTD_parameters) -> size_t;
    pub fn ZSTD_compress_usingCDict_advanced(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ZSTD_CDict, arg6: ZSTD_frameParameters) -> size_t;
    pub fn ZSTD_CCtx_loadDictionary_byReference(arg0: *mut ZSTD_CCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_CCtx_loadDictionary_advanced(arg0: *mut ZSTD_CCtx, arg1: *const ::core::ffi::c_void, arg2: size_t, arg3: ZSTD_dictLoadMethod_e, arg4: ZSTD_dictContentType_e) -> size_t;
    pub fn ZSTD_CCtx_refPrefix_advanced(arg0: *mut ZSTD_CCtx, arg1: *const ::core::ffi::c_void, arg2: size_t, arg3: ZSTD_dictContentType_e) -> size_t;
    pub fn ZSTD_CCtx_getParameter(arg0: *const ZSTD_CCtx, arg1: ZSTD_cParameter, arg2: *mut ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_createCCtxParams() -> *mut ZSTD_CCtx_params;
    pub fn ZSTD_freeCCtxParams(arg0: *mut ZSTD_CCtx_params) -> size_t;
    pub fn ZSTD_CCtxParams_reset(arg0: *mut ZSTD_CCtx_params) -> size_t;
    pub fn ZSTD_CCtxParams_init(arg0: *mut ZSTD_CCtx_params, arg1: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_CCtxParams_init_advanced(arg0: *mut ZSTD_CCtx_params, arg1: ZSTD_parameters) -> size_t;
    pub fn ZSTD_CCtxParams_setParameter(arg0: *mut ZSTD_CCtx_params, arg1: ZSTD_cParameter, arg2: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_CCtxParams_getParameter(arg0: *const ZSTD_CCtx_params, arg1: ZSTD_cParameter, arg2: *mut ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_CCtx_setParametersUsingCCtxParams(arg0: *mut ZSTD_CCtx, arg1: *const ZSTD_CCtx_params) -> size_t;
    pub fn ZSTD_compressStream2_simpleArgs(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *mut size_t, arg4: *const ::core::ffi::c_void, arg5: size_t, arg6: *mut size_t, arg7: ZSTD_EndDirective) -> size_t;
    pub fn ZSTD_isFrame(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_uint;
    pub fn ZSTD_createDDict_byReference(arg0: *const ::core::ffi::c_void, arg1: size_t) -> *mut ZSTD_DDict;
    pub fn ZSTD_DCtx_loadDictionary_byReference(arg0: *mut ZSTD_DCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_DCtx_loadDictionary_advanced(arg0: *mut ZSTD_DCtx, arg1: *const ::core::ffi::c_void, arg2: size_t, arg3: ZSTD_dictLoadMethod_e, arg4: ZSTD_dictContentType_e) -> size_t;
    pub fn ZSTD_DCtx_refPrefix_advanced(arg0: *mut ZSTD_DCtx, arg1: *const ::core::ffi::c_void, arg2: size_t, arg3: ZSTD_dictContentType_e) -> size_t;
    pub fn ZSTD_DCtx_setMaxWindowSize(arg0: *mut ZSTD_DCtx, arg1: size_t) -> size_t;
    pub fn ZSTD_DCtx_getParameter(arg0: *mut ZSTD_DCtx, arg1: ZSTD_dParameter, arg2: *mut ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_DCtx_setFormat(arg0: *mut ZSTD_DCtx, arg1: ZSTD_format_e) -> size_t;
    pub fn ZSTD_decompressStream_simpleArgs(arg0: *mut ZSTD_DCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *mut size_t, arg4: *const ::core::ffi::c_void, arg5: size_t, arg6: *mut size_t) -> size_t;
    pub fn ZSTD_initCStream_srcSize(arg0: *mut ZSTD_CStream, arg1: ::core::ffi::c_int, arg2: ::core::ffi::c_ulonglong) -> size_t;
    pub fn ZSTD_initCStream_usingDict(arg0: *mut ZSTD_CStream, arg1: *const ::core::ffi::c_void, arg2: size_t, arg3: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_initCStream_advanced(arg0: *mut ZSTD_CStream, arg1: *const ::core::ffi::c_void, arg2: size_t, arg3: ZSTD_parameters, arg4: ::core::ffi::c_ulonglong) -> size_t;
    pub fn ZSTD_initCStream_usingCDict(arg0: *mut ZSTD_CStream, arg1: *const ZSTD_CDict) -> size_t;
    pub fn ZSTD_initCStream_usingCDict_advanced(arg0: *mut ZSTD_CStream, arg1: *const ZSTD_CDict, arg2: ZSTD_frameParameters, arg3: ::core::ffi::c_ulonglong) -> size_t;
    pub fn ZSTD_resetCStream(arg0: *mut ZSTD_CStream, arg1: ::core::ffi::c_ulonglong) -> size_t;
    pub fn ZSTD_getFrameProgression(arg0: *const ZSTD_CCtx) -> ZSTD_frameProgression;
    pub fn ZSTD_toFlushNow(arg0: *mut ZSTD_CCtx) -> size_t;
    pub fn ZSTD_initDStream_usingDict(arg0: *mut ZSTD_DStream, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_initDStream_usingDDict(arg0: *mut ZSTD_DStream, arg1: *const ZSTD_DDict) -> size_t;
    pub fn ZSTD_resetDStream(arg0: *mut ZSTD_DStream) -> size_t;
    pub fn ZSTD_registerSequenceProducer(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: ZSTD_sequenceProducer_F);
    pub fn ZSTD_CCtxParams_registerSequenceProducer(arg0: *mut ZSTD_CCtx_params, arg1: *mut ::core::ffi::c_void, arg2: ZSTD_sequenceProducer_F);
    pub fn ZSTD_compressBegin(arg0: *mut ZSTD_CCtx, arg1: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_compressBegin_usingDict(arg0: *mut ZSTD_CCtx, arg1: *const ::core::ffi::c_void, arg2: size_t, arg3: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_compressBegin_usingCDict(arg0: *mut ZSTD_CCtx, arg1: *const ZSTD_CDict) -> size_t;
    pub fn ZSTD_copyCCtx(arg0: *mut ZSTD_CCtx, arg1: *const ZSTD_CCtx, arg2: ::core::ffi::c_ulonglong) -> size_t;
    pub fn ZSTD_compressContinue(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_compressEnd(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_compressBegin_advanced(arg0: *mut ZSTD_CCtx, arg1: *const ::core::ffi::c_void, arg2: size_t, arg3: ZSTD_parameters, arg4: ::core::ffi::c_ulonglong) -> size_t;
    pub fn ZSTD_compressBegin_usingCDict_advanced(arg0: *mut ZSTD_CCtx, arg1: *const ZSTD_CDict, arg2: ZSTD_frameParameters, arg3: ::core::ffi::c_ulonglong) -> size_t;
    pub fn ZSTD_decodingBufferSize_min(arg0: ::core::ffi::c_ulonglong, arg1: ::core::ffi::c_ulonglong) -> size_t;
    pub fn ZSTD_decompressBegin(arg0: *mut ZSTD_DCtx) -> size_t;
    pub fn ZSTD_decompressBegin_usingDict(arg0: *mut ZSTD_DCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_decompressBegin_usingDDict(arg0: *mut ZSTD_DCtx, arg1: *const ZSTD_DDict) -> size_t;
    pub fn ZSTD_nextSrcSizeToDecompress(arg0: *mut ZSTD_DCtx) -> size_t;
    pub fn ZSTD_decompressContinue(arg0: *mut ZSTD_DCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_copyDCtx(arg0: *mut ZSTD_DCtx, arg1: *const ZSTD_DCtx);
    pub fn ZSTD_nextInputType(arg0: *mut ZSTD_DCtx) -> ZSTD_nextInputType_e;
    pub fn ZSTD_getBlockSize(arg0: *const ZSTD_CCtx) -> size_t;
    pub fn ZSTD_compressBlock(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_decompressBlock(arg0: *mut ZSTD_DCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_insertBlock(arg0: *mut ZSTD_DCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZDICT_trainFromBuffer(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: *const size_t, arg4: ::core::ffi::c_uint) -> size_t;
    pub fn ZDICT_finalizeDictionary(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: size_t, arg4: *const ::core::ffi::c_void, arg5: *const size_t, arg6: ::core::ffi::c_uint, arg7: ZDICT_params_t) -> size_t;
    pub fn ZDICT_getDictID(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_uint;
    pub fn ZDICT_getDictHeaderSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> size_t;
    pub fn ZDICT_isError(arg0: size_t) -> ::core::ffi::c_uint;
    pub fn ZDICT_getErrorName(arg0: size_t) -> *const ::core::ffi::c_char;
    pub fn ZDICT_trainFromBuffer_cover(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: *const size_t, arg4: ::core::ffi::c_uint, arg5: ZDICT_cover_params_t) -> size_t;
    pub fn ZDICT_optimizeTrainFromBuffer_cover(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: *const size_t, arg4: ::core::ffi::c_uint, arg5: *mut ZDICT_cover_params_t) -> size_t;
    pub fn ZDICT_trainFromBuffer_fastCover(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: *const size_t, arg4: ::core::ffi::c_uint, arg5: ZDICT_fastCover_params_t) -> size_t;
    pub fn ZDICT_optimizeTrainFromBuffer_fastCover(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: *const size_t, arg4: ::core::ffi::c_uint, arg5: *mut ZDICT_fastCover_params_t) -> size_t;
    pub fn ZDICT_trainFromBuffer_legacy(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: *const size_t, arg4: ::core::ffi::c_uint, arg5: ZDICT_legacy_params_t) -> size_t;
    pub fn ZDICT_addEntropyTablesFromBuffer(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: *const size_t, arg5: ::core::ffi::c_uint) -> size_t;
}
pub const CHAR_BIT: ::core::primitive::u32 = 8;
pub const CHAR_MAX: ::core::primitive::u32 = 127;
pub const CHAR_MIN: ::core::primitive::i32 = -128;
pub const INT_MAX: ::core::primitive::u32 = 2147483647;
pub const INT_MIN: ::core::primitive::i32 = -2147483648;
pub const LLONG_MAX: ::core::primitive::u64 = 9223372036854775807;
pub const LLONG_MIN: ::core::primitive::i64 = -9223372036854775808;
pub const LONG_MAX: ::core::primitive::u64 = 9223372036854775807;
pub const LONG_MIN: ::core::primitive::i64 = -9223372036854775808;
pub const SCHAR_MAX: ::core::primitive::u32 = 127;
pub const SCHAR_MIN: ::core::primitive::i32 = -128;
pub const SHRT_MAX: ::core::primitive::u32 = 32767;
pub const SHRT_MIN: ::core::primitive::i32 = -32768;
pub const UCHAR_MAX: ::core::primitive::u32 = 255;
pub const UINT_MAX: ::core::primitive::u32 = 4294967295;
pub const ULLONG_MAX: ::core::primitive::u64 = 18446744073709551615;
pub const ULONG_MAX: ::core::primitive::u64 = 18446744073709551615;
pub const USHRT_MAX: ::core::primitive::u32 = 65535;
pub const ZDICT_CONTENTSIZE_MIN: ::core::primitive::u32 = 128;
pub const ZDICT_DICTSIZE_MIN: ::core::primitive::u32 = 256;
pub const ZDICT_GCC_VERSION: ::core::primitive::u32 = 402;
pub const ZDICT_STATIC_LINKING_ONLY: ::core::primitive::u32 = 1;
pub const ZSTD_BLOCKSIZELOG_MAX: ::core::primitive::u32 = 17;
pub const ZSTD_BLOCKSIZE_MAX: ::core::primitive::u32 = 131072;
pub const ZSTD_BLOCKSIZE_MAX_MIN: ::core::primitive::u32 = 1024;
pub const ZSTD_BLOCKSPLITTER_LEVEL_MAX: ::core::primitive::u32 = 6;
pub const ZSTD_CHAINLOG_MAX: ::core::primitive::u32 = 30;
pub const ZSTD_CHAINLOG_MAX_32: ::core::primitive::u32 = 29;
pub const ZSTD_CHAINLOG_MAX_64: ::core::primitive::u32 = 30;
pub const ZSTD_CHAINLOG_MIN: ::core::primitive::u32 = 6;
pub const ZSTD_CLEVEL_DEFAULT: ::core::primitive::u32 = 3;
pub const ZSTD_CONTENTSIZE_ERROR: ::core::primitive::u64 = 18446744073709551614;
pub const ZSTD_CONTENTSIZE_UNKNOWN: ::core::primitive::u64 = 18446744073709551615;
pub const ZSTD_FRAMEHEADERSIZE_MAX: ::core::primitive::u32 = 18;
pub const ZSTD_HASHLOG_MAX: ::core::primitive::u32 = 30;
pub const ZSTD_HASHLOG_MIN: ::core::primitive::u32 = 6;
pub const ZSTD_LDM_BUCKETSIZELOG_MAX: ::core::primitive::u32 = 8;
pub const ZSTD_LDM_BUCKETSIZELOG_MIN: ::core::primitive::u32 = 1;
pub const ZSTD_LDM_HASHLOG_MAX: ::core::primitive::u32 = 30;
pub const ZSTD_LDM_HASHLOG_MIN: ::core::primitive::u32 = 6;
pub const ZSTD_LDM_HASHRATELOG_MAX: ::core::primitive::u32 = 25;
pub const ZSTD_LDM_HASHRATELOG_MIN: ::core::primitive::u32 = 0;
pub const ZSTD_LDM_MINMATCH_MAX: ::core::primitive::u32 = 4096;
pub const ZSTD_LDM_MINMATCH_MIN: ::core::primitive::u32 = 4;
pub const ZSTD_MAGICNUMBER: ::core::primitive::u32 = 4247762216;
pub const ZSTD_MAGIC_DICTIONARY: ::core::primitive::u32 = 3962610743;
pub const ZSTD_MAGIC_SKIPPABLE_MASK: ::core::primitive::u32 = 4294967280;
pub const ZSTD_MAGIC_SKIPPABLE_START: ::core::primitive::u32 = 407710288;
pub const ZSTD_MAX_INPUT_SIZE: ::core::primitive::u64 = 18374966859414961920;
pub const ZSTD_MINMATCH_MAX: ::core::primitive::u32 = 7;
pub const ZSTD_MINMATCH_MIN: ::core::primitive::u32 = 3;
pub const ZSTD_OVERLAPLOG_MAX: ::core::primitive::u32 = 9;
pub const ZSTD_OVERLAPLOG_MIN: ::core::primitive::u32 = 0;
pub const ZSTD_RUST_BINDINGS_EXPERIMENTAL: ::core::primitive::u32 = 1;
pub const ZSTD_SEARCHLOG_MAX: ::core::primitive::u32 = 30;
pub const ZSTD_SEARCHLOG_MIN: ::core::primitive::u32 = 1;
pub const ZSTD_SEQUENCE_PRODUCER_ERROR: ::core::primitive::u64 = 18446744073709551615;
pub const ZSTD_SKIPPABLEHEADERSIZE: ::core::primitive::u32 = 8;
pub const ZSTD_SRCSIZEHINT_MAX: ::core::primitive::u32 = 2147483647;
pub const ZSTD_SRCSIZEHINT_MIN: ::core::primitive::u32 = 0;
pub const ZSTD_STATIC_LINKING_ONLY: ::core::primitive::u32 = 1;
pub const ZSTD_STRATEGY_MAX: ::core::primitive::u32 = 9;
pub const ZSTD_STRATEGY_MIN: ::core::primitive::u32 = 1;
pub const ZSTD_TARGETCBLOCKSIZE_MAX: ::core::primitive::u32 = 131072;
pub const ZSTD_TARGETCBLOCKSIZE_MIN: ::core::primitive::u32 = 1340;
pub const ZSTD_TARGETLENGTH_MAX: ::core::primitive::u32 = 131072;
pub const ZSTD_TARGETLENGTH_MIN: ::core::primitive::u32 = 0;
pub const ZSTD_VERSION_MAJOR: ::core::primitive::u32 = 1;
pub const ZSTD_VERSION_MINOR: ::core::primitive::u32 = 5;
pub const ZSTD_VERSION_NUMBER: ::core::primitive::u32 = 10507;
pub const ZSTD_VERSION_RELEASE: ::core::primitive::u32 = 7;
pub const ZSTD_VERSION_STRING: &[::core::primitive::u8; 6] = &[49, 46, 53, 46, 55, 0];
pub const ZSTD_WINDOWLOG_LIMIT_DEFAULT: ::core::primitive::u32 = 27;
pub const ZSTD_WINDOWLOG_MAX: ::core::primitive::u32 = 31;
pub const ZSTD_WINDOWLOG_MAX_32: ::core::primitive::u32 = 30;
pub const ZSTD_WINDOWLOG_MAX_64: ::core::primitive::u32 = 31;
pub const ZSTD_WINDOWLOG_MIN: ::core::primitive::u32 = 10;
pub const ZSTD_c_blockDelimiters: ::core::primitive::u32 = 1008;
pub const ZSTD_c_blockSplitterLevel: ::core::primitive::u32 = 1017;
pub const ZSTD_c_deterministicRefPrefix: ::core::primitive::u32 = 1012;
pub const ZSTD_c_enableDedicatedDictSearch: ::core::primitive::u32 = 1005;
pub const ZSTD_c_enableSeqProducerFallback: ::core::primitive::u32 = 1014;
pub const ZSTD_c_forceAttachDict: ::core::primitive::u32 = 1001;
pub const ZSTD_c_forceMaxWindow: ::core::primitive::u32 = 1000;
pub const ZSTD_c_format: ::core::primitive::u32 = 10;
pub const ZSTD_c_literalCompressionMode: ::core::primitive::u32 = 1002;
pub const ZSTD_c_maxBlockSize: ::core::primitive::u32 = 1015;
pub const ZSTD_c_prefetchCDictTables: ::core::primitive::u32 = 1013;
pub const ZSTD_c_repcodeResolution: ::core::primitive::u32 = 1016;
pub const ZSTD_c_rsyncable: ::core::primitive::u32 = 500;
pub const ZSTD_c_searchForExternalRepcodes: ::core::primitive::u32 = 1016;
pub const ZSTD_c_splitAfterSequences: ::core::primitive::u32 = 1010;
pub const ZSTD_c_srcSizeHint: ::core::primitive::u32 = 1004;
pub const ZSTD_c_stableInBuffer: ::core::primitive::u32 = 1006;
pub const ZSTD_c_stableOutBuffer: ::core::primitive::u32 = 1007;
pub const ZSTD_c_useRowMatchFinder: ::core::primitive::u32 = 1011;
pub const ZSTD_c_validateSequences: ::core::primitive::u32 = 1009;
pub const ZSTD_d_disableHuffmanAssembly: ::core::primitive::u32 = 1004;
pub const ZSTD_d_forceIgnoreChecksum: ::core::primitive::u32 = 1002;
pub const ZSTD_d_format: ::core::primitive::u32 = 1000;
pub const ZSTD_d_maxBlockSize: ::core::primitive::u32 = 1005;
pub const ZSTD_d_refMultipleDDicts: ::core::primitive::u32 = 1003;
pub const ZSTD_d_stableOutBuffer: ::core::primitive::u32 = 1001;
pub const _GCC_LIMITS_H_: ::core::primitive::u32 = 1;
pub const _LP64: ::core::primitive::u32 = 1;
pub const linux: ::core::primitive::u32 = 1;
pub const unix: ::core::primitive::u32 = 1;
