[package]
name = "toucan_parser"
version.workspace = true
edition = "2015"
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors = ["Vickenty Fesunov <kent@setattr.net>"]
description = "C parser used by Toucan, derived from lang-c"
include = ["/src/**/*.rs", "/reftests/*.c", "/tests/**/*.rs", "/grammar.*", "/Makefile", "/Cargo.toml", "/LICENSE*", "/README.md", "/UPSTREAM.md"]

[features]
dev-pegviz = []

[lints.rust]
unsafe_code = "forbid"
