[package]
name = "toucan-aws-lc-consumer"
version = "0.0.0"
edition = "2021"
rust-version = "1.71"
publish = false

[workspace]

[dependencies]
aws-lc-rs = { version = "=1.18.0", default-features = false, features = ["aws-lc-sys", "prebuilt-nasm", "bindgen"] }
aws-lc-sys = { version = "=0.44.0", default-features = false }
