// Generated by Toucan for i686-unknown-linux-gnu.
// Do not edit.

#[cfg(not(all(target_arch = "x86", target_os = "linux", target_env = "gnu")))]
compile_error!("these C bindings were generated for a different target");

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_CCtx_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_DCtx_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct __toucan_record_2 {
    pub error: size_t,
    pub lowerBound: ::core::ffi::c_int,
    pub upperBound: ::core::ffi::c_int,
}
const _: () = {
    assert!(::core::mem::size_of::<__toucan_record_2>() == 12);
    assert!(::core::mem::align_of::<__toucan_record_2>() == 4);
    assert!(::core::mem::offset_of!(__toucan_record_2, error) == 0);
    assert!(::core::mem::offset_of!(__toucan_record_2, lowerBound) == 4);
    assert!(::core::mem::offset_of!(__toucan_record_2, upperBound) == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_inBuffer_s {
    pub src: *const ::core::ffi::c_void,
    pub size: size_t,
    pub pos: size_t,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_inBuffer_s>() == 12);
    assert!(::core::mem::align_of::<ZSTD_inBuffer_s>() == 4);
    assert!(::core::mem::offset_of!(ZSTD_inBuffer_s, src) == 0);
    assert!(::core::mem::offset_of!(ZSTD_inBuffer_s, size) == 4);
    assert!(::core::mem::offset_of!(ZSTD_inBuffer_s, pos) == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_outBuffer_s {
    pub dst: *mut ::core::ffi::c_void,
    pub size: size_t,
    pub pos: size_t,
}
const _: () = {
    assert!(::core::mem::size_of::<ZSTD_outBuffer_s>() == 12);
    assert!(::core::mem::align_of::<ZSTD_outBuffer_s>() == 4);
    assert!(::core::mem::offset_of!(ZSTD_outBuffer_s, dst) == 0);
    assert!(::core::mem::offset_of!(ZSTD_outBuffer_s, size) == 4);
    assert!(::core::mem::offset_of!(ZSTD_outBuffer_s, pos) == 8);
};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_CDict_s { _private: [::core::primitive::u8; 0] }

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSTD_DDict_s { _private: [::core::primitive::u8; 0] }

pub type __toucan_enum_0 = ::core::primitive::u32;
pub type __toucan_enum_1 = ::core::primitive::u32;
pub type __toucan_enum_2 = ::core::primitive::u32;
pub type __toucan_enum_3 = ::core::primitive::u32;
pub type __toucan_enum_4 = ::core::primitive::u32;
pub type __toucan_enum_5 = ::core::primitive::u32;
pub type ZSTD_CCtx = ZSTD_CCtx_s;
pub type ZSTD_CDict = ZSTD_CDict_s;
pub type ZSTD_CStream = ZSTD_CCtx;
pub type ZSTD_DCtx = ZSTD_DCtx_s;
pub type ZSTD_DDict = ZSTD_DDict_s;
pub type ZSTD_DStream = ZSTD_DCtx;
pub type ZSTD_EndDirective = __toucan_enum_5;
pub type ZSTD_ErrorCode = __toucan_enum_0;
pub type ZSTD_ResetDirective = __toucan_enum_3;
pub type ZSTD_bounds = __toucan_record_2;
pub type ZSTD_cParameter = __toucan_enum_2;
pub type ZSTD_dParameter = __toucan_enum_4;
pub type ZSTD_inBuffer = ZSTD_inBuffer_s;
pub type ZSTD_outBuffer = ZSTD_outBuffer_s;
pub type ZSTD_strategy = __toucan_enum_1;
pub type ptrdiff_t = ::core::ffi::c_int;
pub type size_t = ::core::ffi::c_uint;
pub type wchar_t = ::core::ffi::c_int;
pub const ZSTD_btlazy2: ::core::primitive::u32 = 6;
pub const ZSTD_btopt: ::core::primitive::u32 = 7;
pub const ZSTD_btultra: ::core::primitive::u32 = 8;
pub const ZSTD_btultra2: ::core::primitive::u32 = 9;
pub const ZSTD_c_chainLog: ::core::primitive::u32 = 103;
pub const ZSTD_c_checksumFlag: ::core::primitive::u32 = 201;
pub const ZSTD_c_compressionLevel: ::core::primitive::u32 = 100;
pub const ZSTD_c_contentSizeFlag: ::core::primitive::u32 = 200;
pub const ZSTD_c_dictIDFlag: ::core::primitive::u32 = 202;
pub const ZSTD_c_enableLongDistanceMatching: ::core::primitive::u32 = 160;
pub const ZSTD_c_experimentalParam1: ::core::primitive::u32 = 500;
pub const ZSTD_c_experimentalParam10: ::core::primitive::u32 = 1007;
pub const ZSTD_c_experimentalParam11: ::core::primitive::u32 = 1008;
pub const ZSTD_c_experimentalParam12: ::core::primitive::u32 = 1009;
pub const ZSTD_c_experimentalParam13: ::core::primitive::u32 = 1010;
pub const ZSTD_c_experimentalParam14: ::core::primitive::u32 = 1011;
pub const ZSTD_c_experimentalParam15: ::core::primitive::u32 = 1012;
pub const ZSTD_c_experimentalParam16: ::core::primitive::u32 = 1013;
pub const ZSTD_c_experimentalParam17: ::core::primitive::u32 = 1014;
pub const ZSTD_c_experimentalParam18: ::core::primitive::u32 = 1015;
pub const ZSTD_c_experimentalParam19: ::core::primitive::u32 = 1016;
pub const ZSTD_c_experimentalParam2: ::core::primitive::u32 = 10;
pub const ZSTD_c_experimentalParam20: ::core::primitive::u32 = 1017;
pub const ZSTD_c_experimentalParam3: ::core::primitive::u32 = 1000;
pub const ZSTD_c_experimentalParam4: ::core::primitive::u32 = 1001;
pub const ZSTD_c_experimentalParam5: ::core::primitive::u32 = 1002;
pub const ZSTD_c_experimentalParam7: ::core::primitive::u32 = 1004;
pub const ZSTD_c_experimentalParam8: ::core::primitive::u32 = 1005;
pub const ZSTD_c_experimentalParam9: ::core::primitive::u32 = 1006;
pub const ZSTD_c_hashLog: ::core::primitive::u32 = 102;
pub const ZSTD_c_jobSize: ::core::primitive::u32 = 401;
pub const ZSTD_c_ldmBucketSizeLog: ::core::primitive::u32 = 163;
pub const ZSTD_c_ldmHashLog: ::core::primitive::u32 = 161;
pub const ZSTD_c_ldmHashRateLog: ::core::primitive::u32 = 164;
pub const ZSTD_c_ldmMinMatch: ::core::primitive::u32 = 162;
pub const ZSTD_c_minMatch: ::core::primitive::u32 = 105;
pub const ZSTD_c_nbWorkers: ::core::primitive::u32 = 400;
pub const ZSTD_c_overlapLog: ::core::primitive::u32 = 402;
pub const ZSTD_c_searchLog: ::core::primitive::u32 = 104;
pub const ZSTD_c_strategy: ::core::primitive::u32 = 107;
pub const ZSTD_c_targetCBlockSize: ::core::primitive::u32 = 130;
pub const ZSTD_c_targetLength: ::core::primitive::u32 = 106;
pub const ZSTD_c_windowLog: ::core::primitive::u32 = 101;
pub const ZSTD_d_experimentalParam1: ::core::primitive::u32 = 1000;
pub const ZSTD_d_experimentalParam2: ::core::primitive::u32 = 1001;
pub const ZSTD_d_experimentalParam3: ::core::primitive::u32 = 1002;
pub const ZSTD_d_experimentalParam4: ::core::primitive::u32 = 1003;
pub const ZSTD_d_experimentalParam5: ::core::primitive::u32 = 1004;
pub const ZSTD_d_experimentalParam6: ::core::primitive::u32 = 1005;
pub const ZSTD_d_windowLogMax: ::core::primitive::u32 = 100;
pub const ZSTD_dfast: ::core::primitive::u32 = 2;
pub const ZSTD_e_continue: ::core::primitive::u32 = 0;
pub const ZSTD_e_end: ::core::primitive::u32 = 2;
pub const ZSTD_e_flush: ::core::primitive::u32 = 1;
pub const ZSTD_error_GENERIC: ::core::primitive::u32 = 1;
pub const ZSTD_error_cannotProduce_uncompressedBlock: ::core::primitive::u32 = 49;
pub const ZSTD_error_checksum_wrong: ::core::primitive::u32 = 22;
pub const ZSTD_error_corruption_detected: ::core::primitive::u32 = 20;
pub const ZSTD_error_dictionaryCreation_failed: ::core::primitive::u32 = 34;
pub const ZSTD_error_dictionary_corrupted: ::core::primitive::u32 = 30;
pub const ZSTD_error_dictionary_wrong: ::core::primitive::u32 = 32;
pub const ZSTD_error_dstBuffer_null: ::core::primitive::u32 = 74;
pub const ZSTD_error_dstBuffer_wrong: ::core::primitive::u32 = 104;
pub const ZSTD_error_dstSize_tooSmall: ::core::primitive::u32 = 70;
pub const ZSTD_error_externalSequences_invalid: ::core::primitive::u32 = 107;
pub const ZSTD_error_frameIndex_tooLarge: ::core::primitive::u32 = 100;
pub const ZSTD_error_frameParameter_unsupported: ::core::primitive::u32 = 14;
pub const ZSTD_error_frameParameter_windowTooLarge: ::core::primitive::u32 = 16;
pub const ZSTD_error_init_missing: ::core::primitive::u32 = 62;
pub const ZSTD_error_literals_headerWrong: ::core::primitive::u32 = 24;
pub const ZSTD_error_maxCode: ::core::primitive::u32 = 120;
pub const ZSTD_error_maxSymbolValue_tooLarge: ::core::primitive::u32 = 46;
pub const ZSTD_error_maxSymbolValue_tooSmall: ::core::primitive::u32 = 48;
pub const ZSTD_error_memory_allocation: ::core::primitive::u32 = 64;
pub const ZSTD_error_noForwardProgress_destFull: ::core::primitive::u32 = 80;
pub const ZSTD_error_noForwardProgress_inputEmpty: ::core::primitive::u32 = 82;
pub const ZSTD_error_no_error: ::core::primitive::u32 = 0;
pub const ZSTD_error_parameter_combination_unsupported: ::core::primitive::u32 = 41;
pub const ZSTD_error_parameter_outOfBound: ::core::primitive::u32 = 42;
pub const ZSTD_error_parameter_unsupported: ::core::primitive::u32 = 40;
pub const ZSTD_error_prefix_unknown: ::core::primitive::u32 = 10;
pub const ZSTD_error_seekableIO: ::core::primitive::u32 = 102;
pub const ZSTD_error_sequenceProducer_failed: ::core::primitive::u32 = 106;
pub const ZSTD_error_srcBuffer_wrong: ::core::primitive::u32 = 105;
pub const ZSTD_error_srcSize_wrong: ::core::primitive::u32 = 72;
pub const ZSTD_error_stabilityCondition_notRespected: ::core::primitive::u32 = 50;
pub const ZSTD_error_stage_wrong: ::core::primitive::u32 = 60;
pub const ZSTD_error_tableLog_tooLarge: ::core::primitive::u32 = 44;
pub const ZSTD_error_version_unsupported: ::core::primitive::u32 = 12;
pub const ZSTD_error_workSpace_tooSmall: ::core::primitive::u32 = 66;
pub const ZSTD_fast: ::core::primitive::u32 = 1;
pub const ZSTD_greedy: ::core::primitive::u32 = 3;
pub const ZSTD_lazy: ::core::primitive::u32 = 4;
pub const ZSTD_lazy2: ::core::primitive::u32 = 5;
pub const ZSTD_reset_parameters: ::core::primitive::u32 = 2;
pub const ZSTD_reset_session_and_parameters: ::core::primitive::u32 = 3;
pub const ZSTD_reset_session_only: ::core::primitive::u32 = 1;

unsafe extern "C" {
    pub fn ZSTD_getErrorString(arg0: ZSTD_ErrorCode) -> *const ::core::ffi::c_char;
    pub fn ZSTD_versionNumber() -> ::core::ffi::c_uint;
    pub fn ZSTD_versionString() -> *const ::core::ffi::c_char;
    pub fn ZSTD_compress(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: size_t, arg4: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_decompress(arg0: *mut ::core::ffi::c_void, arg1: size_t, arg2: *const ::core::ffi::c_void, arg3: size_t) -> size_t;
    pub fn ZSTD_getFrameContentSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_ulonglong;
    pub fn ZSTD_getDecompressedSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_ulonglong;
    pub fn ZSTD_findFrameCompressedSize(arg0: *const ::core::ffi::c_void, arg1: size_t) -> size_t;
    pub fn ZSTD_compressBound(arg0: size_t) -> size_t;
    pub fn ZSTD_isError(arg0: size_t) -> ::core::ffi::c_uint;
    pub fn ZSTD_getErrorCode(arg0: size_t) -> ZSTD_ErrorCode;
    pub fn ZSTD_getErrorName(arg0: size_t) -> *const ::core::ffi::c_char;
    pub fn ZSTD_minCLevel() -> ::core::ffi::c_int;
    pub fn ZSTD_maxCLevel() -> ::core::ffi::c_int;
    pub fn ZSTD_defaultCLevel() -> ::core::ffi::c_int;
    pub fn ZSTD_createCCtx() -> *mut ZSTD_CCtx;
    pub fn ZSTD_freeCCtx(arg0: *mut ZSTD_CCtx) -> size_t;
    pub fn ZSTD_compressCCtx(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_createDCtx() -> *mut ZSTD_DCtx;
    pub fn ZSTD_freeDCtx(arg0: *mut ZSTD_DCtx) -> size_t;
    pub fn ZSTD_decompressDCtx(arg0: *mut ZSTD_DCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_cParam_getBounds(arg0: ZSTD_cParameter) -> ZSTD_bounds;
    pub fn ZSTD_CCtx_setParameter(arg0: *mut ZSTD_CCtx, arg1: ZSTD_cParameter, arg2: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_CCtx_setPledgedSrcSize(arg0: *mut ZSTD_CCtx, arg1: ::core::ffi::c_ulonglong) -> size_t;
    pub fn ZSTD_CCtx_reset(arg0: *mut ZSTD_CCtx, arg1: ZSTD_ResetDirective) -> size_t;
    pub fn ZSTD_compress2(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t) -> size_t;
    pub fn ZSTD_dParam_getBounds(arg0: ZSTD_dParameter) -> ZSTD_bounds;
    pub fn ZSTD_DCtx_setParameter(arg0: *mut ZSTD_DCtx, arg1: ZSTD_dParameter, arg2: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_DCtx_reset(arg0: *mut ZSTD_DCtx, arg1: ZSTD_ResetDirective) -> size_t;
    pub fn ZSTD_createCStream() -> *mut ZSTD_CStream;
    pub fn ZSTD_freeCStream(arg0: *mut ZSTD_CStream) -> size_t;
    pub fn ZSTD_compressStream2(arg0: *mut ZSTD_CCtx, arg1: *mut ZSTD_outBuffer, arg2: *mut ZSTD_inBuffer, arg3: ZSTD_EndDirective) -> size_t;
    pub fn ZSTD_CStreamInSize() -> size_t;
    pub fn ZSTD_CStreamOutSize() -> size_t;
    pub fn ZSTD_initCStream(arg0: *mut ZSTD_CStream, arg1: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_compressStream(arg0: *mut ZSTD_CStream, arg1: *mut ZSTD_outBuffer, arg2: *mut ZSTD_inBuffer) -> size_t;
    pub fn ZSTD_flushStream(arg0: *mut ZSTD_CStream, arg1: *mut ZSTD_outBuffer) -> size_t;
    pub fn ZSTD_endStream(arg0: *mut ZSTD_CStream, arg1: *mut ZSTD_outBuffer) -> size_t;
    pub fn ZSTD_createDStream() -> *mut ZSTD_DStream;
    pub fn ZSTD_freeDStream(arg0: *mut ZSTD_DStream) -> size_t;
    pub fn ZSTD_initDStream(arg0: *mut ZSTD_DStream) -> size_t;
    pub fn ZSTD_decompressStream(arg0: *mut ZSTD_DStream, arg1: *mut ZSTD_outBuffer, arg2: *mut ZSTD_inBuffer) -> size_t;
    pub fn ZSTD_DStreamInSize() -> size_t;
    pub fn ZSTD_DStreamOutSize() -> size_t;
    pub fn ZSTD_compress_usingDict(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ::core::ffi::c_void, arg6: size_t, arg7: ::core::ffi::c_int) -> size_t;
    pub fn ZSTD_decompress_usingDict(arg0: *mut ZSTD_DCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ::core::ffi::c_void, arg6: size_t) -> size_t;
    pub fn ZSTD_createCDict(arg0: *const ::core::ffi::c_void, arg1: size_t, arg2: ::core::ffi::c_int) -> *mut ZSTD_CDict;
    pub fn ZSTD_freeCDict(arg0: *mut ZSTD_CDict) -> size_t;
    pub fn ZSTD_compress_usingCDict(arg0: *mut ZSTD_CCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ZSTD_CDict) -> size_t;
    pub fn ZSTD_createDDict(arg0: *const ::core::ffi::c_void, arg1: size_t) -> *mut ZSTD_DDict;
    pub fn ZSTD_freeDDict(arg0: *mut ZSTD_DDict) -> size_t;
    pub fn ZSTD_decompress_usingDDict(arg0: *mut ZSTD_DCtx, arg1: *mut ::core::ffi::c_void, arg2: size_t, arg3: *const ::core::ffi::c_void, arg4: size_t, arg5: *const ZSTD_DDict) -> size_t;
    pub fn ZSTD_getDictID_fromDict(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_uint;
    pub fn ZSTD_getDictID_fromCDict(arg0: *const ZSTD_CDict) -> ::core::ffi::c_uint;
    pub fn ZSTD_getDictID_fromDDict(arg0: *const ZSTD_DDict) -> ::core::ffi::c_uint;
    pub fn ZSTD_getDictID_fromFrame(arg0: *const ::core::ffi::c_void, arg1: size_t) -> ::core::ffi::c_uint;
    pub fn ZSTD_CCtx_loadDictionary(arg0: *mut ZSTD_CCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_CCtx_refCDict(arg0: *mut ZSTD_CCtx, arg1: *const ZSTD_CDict) -> size_t;
    pub fn ZSTD_CCtx_refPrefix(arg0: *mut ZSTD_CCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_DCtx_loadDictionary(arg0: *mut ZSTD_DCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_DCtx_refDDict(arg0: *mut ZSTD_DCtx, arg1: *const ZSTD_DDict) -> size_t;
    pub fn ZSTD_DCtx_refPrefix(arg0: *mut ZSTD_DCtx, arg1: *const ::core::ffi::c_void, arg2: size_t) -> size_t;
    pub fn ZSTD_sizeof_CCtx(arg0: *const ZSTD_CCtx) -> size_t;
    pub fn ZSTD_sizeof_DCtx(arg0: *const ZSTD_DCtx) -> size_t;
    pub fn ZSTD_sizeof_CStream(arg0: *const ZSTD_CStream) -> size_t;
    pub fn ZSTD_sizeof_DStream(arg0: *const ZSTD_DStream) -> size_t;
    pub fn ZSTD_sizeof_CDict(arg0: *const ZSTD_CDict) -> size_t;
    pub fn ZSTD_sizeof_DDict(arg0: *const ZSTD_DDict) -> size_t;
}
pub const ZSTD_BLOCKSIZELOG_MAX: ::core::primitive::i32 = 17;
pub const ZSTD_BLOCKSIZE_MAX: ::core::primitive::i32 = 131072;
pub const ZSTD_CLEVEL_DEFAULT: ::core::primitive::i32 = 3;
pub const ZSTD_CONTENTSIZE_ERROR: ::core::primitive::u64 = 18446744073709551614;
pub const ZSTD_CONTENTSIZE_UNKNOWN: ::core::primitive::u64 = 18446744073709551615;
pub const ZSTD_MAGICNUMBER: ::core::primitive::u32 = 4247762216;
pub const ZSTD_MAGIC_DICTIONARY: ::core::primitive::u32 = 3962610743;
pub const ZSTD_MAGIC_SKIPPABLE_MASK: ::core::primitive::u32 = 4294967280;
pub const ZSTD_MAGIC_SKIPPABLE_START: ::core::primitive::i32 = 407710288;
pub const ZSTD_MAX_INPUT_SIZE: ::core::primitive::u64 = 4278255360;
pub const ZSTD_VERSION_MAJOR: ::core::primitive::i32 = 1;
pub const ZSTD_VERSION_MINOR: ::core::primitive::i32 = 5;
pub const ZSTD_VERSION_NUMBER: ::core::primitive::i32 = 10507;
pub const ZSTD_VERSION_RELEASE: ::core::primitive::i32 = 7;
pub const ZSTD_VERSION_STRING: &[::core::primitive::u8; 6] = &[49, 46, 53, 46, 55, 0];
pub const _ILP32: ::core::primitive::i32 = 1;
pub const i386: ::core::primitive::i32 = 1;
pub const linux: ::core::primitive::i32 = 1;
pub const unix: ::core::primitive::i32 = 1;
