// Exhaustive AST field schema shared by accounting, views, and structural operations.
// Destructuring in each consumer makes added fields or variants a compile error.
macro_rules! ast_schema {
    () => {
        structure!(Identifier { name: String });
        enumeration!(Constant => ConstantView { Integer(v0: Integer), Float(v0: Float), Character(v0: String) });
        structure!(Integer { base: IntegerBase, number: Box<str>, suffix: IntegerSuffix });
        enumeration!(IntegerBase => IntegerBaseView { Decimal, Octal, Hexadecimal, Binary });
        structure!(IntegerSuffix { size: IntegerSize, unsigned: bool, imaginary: bool });
        enumeration!(IntegerSize => IntegerSizeView { Int, Long, LongLong, Msvc(v0: u8) });
        structure!(Float { base: FloatBase, number: Box<str>, suffix: FloatSuffix });
        enumeration!(FloatBase => FloatBaseView { Decimal, Hexadecimal });
        structure!(FloatSuffix { format: FloatFormat, imaginary: bool });
        enumeration!(FloatFormat => FloatFormatView { Float128, Float, Double, LongDouble, TS18661Format(v0: TS18661FloatType) });
        enumeration!(Expression => ExpressionView { Identifier(v0: Id<Node<Identifier>>), Constant(v0: Id<Node<Constant>>), StringLiteral(v0: Id<Node<StringLiteral>>), GenericSelection(v0: Id<Node<GenericSelection>>), TypesCompatible(v0: Id<Node<TypesCompatibleExpression>>), Choose(v0: Id<Node<ChooseExpression>>), ConvertVector(v0: Id<Node<ConvertVectorExpression>>), Member(v0: Id<Node<MemberExpression>>), Call(v0: Id<Node<CallExpression>>), CompoundLiteral(v0: Id<Node<CompoundLiteral>>), SizeOfTy(v0: Id<Node<SizeOfTy>>), SizeOfVal(v0: Id<Node<SizeOfVal>>), AlignOf(v0: Id<Node<AlignOf>>), UnaryOperator(v0: Id<Node<UnaryOperatorExpression>>), Cast(v0: Id<Node<CastExpression>>), BinaryOperator(v0: Id<Node<BinaryOperatorExpression>>), Conditional(v0: Id<Node<ConditionalExpression>>), Comma(v0: Id<Vec<Node<Expression>>>), OffsetOf(v0: Id<Node<OffsetOfExpression>>), VaArg(v0: Id<Node<VaArgExpression>>), Statement(v0: Id<Node<Statement>>) });
        enumeration!(MemberOperator => MemberOperatorView { Direct, Indirect });
        structure!(TypesCompatibleExpression { left: Node<TypeName>, right: Node<TypeName> });
        structure!(ChooseExpression { condition: Node<Expression>, then_expression: Node<Expression>, else_expression: Node<Expression> });
        structure!(ConvertVectorExpression { expression: Node<Expression>, type_name: Node<TypeName> });
        structure!(GenericSelection { expression: Node<Expression>, associations: Vec<Node<GenericAssociation>> });
        enumeration!(GenericAssociation => GenericAssociationView { Type(v0: Node<GenericAssociationType>), Default(v0: Node<Expression>) });
        structure!(GenericAssociationType { type_name: Node<TypeName>, expression: Node<Expression> });
        structure!(MemberExpression { operator: Node<MemberOperator>, expression: Node<Expression>, identifier: Node<Identifier> });
        structure!(CallExpression { callee: Node<Expression>, arguments: Vec<Node<Expression>> });
        structure!(CompoundLiteral { type_name: Node<TypeName>, initializer_list: Vec<Node<InitializerListItem>> });
        tuple_structure!(SizeOfTy { 0: Node<TypeName> });
        tuple_structure!(SizeOfVal { 0: Node<Expression> });
        structure!(AlignOf { kind: AlignOfKind, operand: AlignOfOperand });
        enumeration!(AlignOfKind => AlignOfKindView { C11, Gnu });
        enumeration!(AlignOfOperand => AlignOfOperandView { TypeName(v0: Id<Node<TypeName>>), Expression(v0: Node<Expression>) });
        enumeration!(UnaryOperator => UnaryOperatorView { PostIncrement, PostDecrement, PreIncrement, PreDecrement, Address, Indirection, Plus, Minus, Complement, Negate, Real, Imaginary });
        structure!(UnaryOperatorExpression { operator: Node<UnaryOperator>, operand: Node<Expression> });
        structure!(CastExpression { type_name: Node<TypeName>, expression: Node<Expression> });
        enumeration!(BinaryOperator => BinaryOperatorView { Index, Multiply, Divide, Modulo, Plus, Minus, ShiftLeft, ShiftRight, Less, Greater, LessOrEqual, GreaterOrEqual, Equals, NotEquals, BitwiseAnd, BitwiseXor, BitwiseOr, LogicalAnd, LogicalOr, Assign, AssignMultiply, AssignDivide, AssignModulo, AssignPlus, AssignMinus, AssignShiftLeft, AssignShiftRight, AssignBitwiseAnd, AssignBitwiseXor, AssignBitwiseOr });
        structure!(BinaryOperatorExpression { operator: Node<BinaryOperator>, lhs: Node<Expression>, rhs: Node<Expression> });
        structure!(ConditionalExpression { condition: Node<Expression>, then_expression: Option<Node<Expression>>, else_expression: Node<Expression> });
        structure!(VaArgExpression { va_list: Node<Expression>, type_name: Node<TypeName> });
        structure!(OffsetOfExpression { type_name: Node<TypeName>, designator: Node<OffsetDesignator> });
        structure!(OffsetDesignator { base: Node<Identifier>, members: Vec<Node<OffsetMember>> });
        enumeration!(OffsetMember => OffsetMemberView { Member(v0: Node<Identifier>), IndirectMember(v0: Node<Identifier>), Index(v0: Node<Expression>) });
        structure!(Declaration { specifiers: Vec<Node<DeclarationSpecifier>>, declarators: Vec<Node<InitDeclarator>> });
        enumeration!(DeclarationSpecifier => DeclarationSpecifierView { StorageClass(v0: Node<StorageClassSpecifier>), TypeSpecifier(v0: Node<TypeSpecifier>), TypeQualifier(v0: Node<TypeQualifier>), Function(v0: Node<FunctionSpecifier>), Alignment(v0: Node<AlignmentSpecifier>), Extension(v0: Vec<Node<Extension>>) });
        structure!(InitDeclarator { declarator: Node<Declarator>, initializer: Option<Node<Initializer>> });
        enumeration!(StorageClassSpecifier => StorageClassSpecifierView { Typedef, Extern, Static, ThreadLocal, GnuThreadLocal, Auto, Register });
        enumeration!(TypeSpecifier => TypeSpecifierView { AutoType, BFloat16, Float128, Void, Char, Short, Int, Int128, MsvcInteger(v0: u8), Long, Float, Double, Signed, Unsigned, Bool, Complex, Atomic(v0: Id<Node<TypeName>>), Struct(v0: Id<Node<StructType>>), Enum(v0: Id<Node<EnumType>>), TypedefName(v0: Node<Identifier>), TypeOf(v0: Id<Node<TypeOf>>), TS18661Float(v0: TS18661FloatType) });
        structure!(TS18661FloatType { format: TS18661FloatFormat, width: usize });
        enumeration!(TS18661FloatFormat => TS18661FloatFormatView { BinaryInterchange, BinaryExtended, DecimalInterchange, DecimalExtended });
        structure!(StructType { extensions: Vec<Node<Extension>>, kind: Node<StructKind>, identifier: Option<Node<Identifier>>, declarations: Option<Vec<Node<StructDeclaration>>> });
        enumeration!(StructKind => StructKindView { Struct, Union });
        enumeration!(StructDeclaration => StructDeclarationView { Field(v0: Node<StructField>), StaticAssert(v0: Node<StaticAssert>) });
        structure!(StructField { specifiers: Vec<Node<SpecifierQualifier>>, declarators: Vec<Node<StructDeclarator>> });
        enumeration!(SpecifierQualifier => SpecifierQualifierView { Alignment(v0: Node<AlignmentSpecifier>), TypeSpecifier(v0: Node<TypeSpecifier>), TypeQualifier(v0: Node<TypeQualifier>), Extension(v0: Vec<Node<Extension>>) });
        structure!(StructDeclarator { declarator: Option<Node<Declarator>>, bit_width: Option<Node<Expression>>, extensions: Vec<Node<Extension>> });
        structure!(EnumType { extensions: Vec<Node<Extension>>, identifier: Option<Node<Identifier>>, enumerators: Vec<Node<Enumerator>> });
        structure!(Enumerator { identifier: Node<Identifier>, expression: Option<Node<Expression>>, extensions: Vec<Node<Extension>> });
        enumeration!(TypeQualifier => TypeQualifierView { Const, Restrict, Volatile, Unaligned, Nonnull, NullUnspecified, Nullable, Atomic });
        enumeration!(FunctionSpecifier => FunctionSpecifierView { Inline, Noreturn });
        enumeration!(AlignmentSpecifier => AlignmentSpecifierView { Type(v0: Id<Node<TypeName>>), Constant(v0: Node<Expression>) });
        structure!(Declarator { kind: Node<DeclaratorKind>, derived: Vec<Node<DerivedDeclarator>>, extensions: Vec<Node<Extension>> });
        enumeration!(DeclaratorKind => DeclaratorKindView { Abstract, Identifier(v0: Node<Identifier>), Declarator(v0: Id<Node<Declarator>>) });
        enumeration!(DerivedDeclarator => DerivedDeclaratorView { Pointer(v0: Vec<Node<PointerQualifier>>), Array(v0: Node<ArrayDeclarator>), Function(v0: Id<Node<FunctionDeclarator>>), KRFunction(v0: Vec<Node<Identifier>>), Block(v0: Vec<Node<PointerQualifier>>) });
        structure!(ArrayDeclarator { qualifiers: Vec<Node<TypeQualifier>>, size: ArraySize });
        structure!(FunctionDeclarator { parameters: Vec<Node<ParameterDeclaration>>, ellipsis: Ellipsis });
        enumeration!(PointerQualifier => PointerQualifierView { TypeQualifier(v0: Node<TypeQualifier>), Extension(v0: Vec<Node<Extension>>), MsvcPointerWidth(v0: u8) });
        enumeration!(ArraySize => ArraySizeView { Unknown, VariableUnknown, VariableExpression(v0: Node<Expression>), StaticExpression(v0: Node<Expression>) });
        structure!(ParameterDeclaration { specifiers: Vec<Node<DeclarationSpecifier>>, declarator: Option<Node<Declarator>>, extensions: Vec<Node<Extension>> });
        enumeration!(Ellipsis => EllipsisView { Some, None });
        structure!(TypeName { specifiers: Vec<Node<SpecifierQualifier>>, declarator: Option<Node<Declarator>> });
        enumeration!(Initializer => InitializerView { Expression(v0: Node<Expression>), List(v0: Id<Vec<Node<InitializerListItem>>>) });
        structure!(InitializerListItem { designation: Vec<Node<Designator>>, initializer: Node<Initializer> });
        enumeration!(Designator => DesignatorView { Index(v0: Node<Expression>), Member(v0: Node<Identifier>), Range(v0: Node<RangeDesignator>) });
        structure!(RangeDesignator { from: Node<Expression>, to: Node<Expression> });
        structure!(StaticAssert { expression: Node<Expression>, message: Node<StringLiteral> });
        enumeration!(Statement => StatementView { Labeled(v0: Id<Node<LabeledStatement>>), Compound(v0: Id<Vec<Node<BlockItem>>>), Expression(v0: Option<Node<Expression>>), Attribute(v0: Vec<Node<Extension>>), If(v0: Id<Node<IfStatement>>), Switch(v0: Id<Node<SwitchStatement>>), While(v0: Id<Node<WhileStatement>>), DoWhile(v0: Id<Node<DoWhileStatement>>), For(v0: Id<Node<ForStatement>>), Goto(v0: Node<Identifier>), Continue, Break, Return(v0: Option<Node<Expression>>), Asm(v0: Node<AsmStatement>) });
        structure!(LabeledStatement { label: Node<Label>, statement: Node<Statement> });
        structure!(IfStatement { condition: Node<Expression>, then_statement: Node<Statement>, else_statement: Option<Node<Statement>> });
        structure!(SwitchStatement { expression: Node<Expression>, statement: Node<Statement> });
        structure!(WhileStatement { expression: Node<Expression>, statement: Node<Statement> });
        structure!(DoWhileStatement { statement: Node<Statement>, expression: Node<Expression> });
        structure!(ForStatement { initializer: Node<ForInitializer>, condition: Option<Node<Expression>>, step: Option<Node<Expression>>, statement: Node<Statement> });
        enumeration!(Label => LabelView { Identifier(v0: Node<Identifier>), Case(v0: Node<Expression>), CaseRange(v0: Node<CaseRange>), Default });
        structure!(CaseRange { low: Node<Expression>, high: Node<Expression> });
        enumeration!(ForInitializer => ForInitializerView { Empty, Expression(v0: Node<Expression>), Declaration(v0: Node<Declaration>), StaticAssert(v0: Node<StaticAssert>) });
        enumeration!(BlockItem => BlockItemView { Declaration(v0: Node<Declaration>), StaticAssert(v0: Node<StaticAssert>), Statement(v0: Node<Statement>) });
        tuple_structure!(TranslationUnit { 0: Vec<Node<ExternalDeclaration>> });
        enumeration!(ExternalDeclaration => ExternalDeclarationView { Declaration(v0: Node<Declaration>), StaticAssert(v0: Node<StaticAssert>), FunctionDefinition(v0: Node<FunctionDefinition>) });
        structure!(FunctionDefinition { specifiers: Vec<Node<DeclarationSpecifier>>, declarator: Node<Declarator>, declarations: Vec<Node<Declaration>>, statement: Node<Statement> });
        enumeration!(Extension => ExtensionView { Attribute(v0: Attribute), CallingConvention(v0: Attribute), Declspec(v0: Attribute), AsmLabel(v0: Node<StringLiteral>), AvailabilityAttribute(v0: Node<AvailabilityAttribute>) });
        structure!(Attribute { name: Node<String>, arguments: Vec<Node<Expression>> });
        structure!(AvailabilityAttribute { platform: Node<Identifier>, clauses: Vec<Node<AvailabilityClause>> });
        enumeration!(AvailabilityClause => AvailabilityClauseView { Introduced(v0: Node<AvailabilityVersion>), Deprecated(v0: Node<AvailabilityVersion>), Obsoleted(v0: Node<AvailabilityVersion>), Unavailable, Message(v0: Node<StringLiteral>), Replacement(v0: Node<StringLiteral>) });
        structure!(AvailabilityVersion { major: String, minor: Option<String>, subminor: Option<String> });
        enumeration!(AsmStatement => AsmStatementView { GnuBasic(v0: Node<StringLiteral>), GnuExtended(v0: GnuExtendedAsmStatement) });
        structure!(GnuExtendedAsmStatement { qualifier: Option<Node<TypeQualifier>>, template: Node<StringLiteral>, outputs: Vec<Node<GnuAsmOperand>>, inputs: Vec<Node<GnuAsmOperand>>, clobbers: Vec<Node<StringLiteral>> });
        structure!(GnuAsmOperand { symbolic_name: Option<Node<Identifier>>, constraints: Node<StringLiteral>, variable_name: Node<Expression> });
        enumeration!(TypeOf => TypeOfView { Expression(v0: Node<Expression>), Type(v0: Node<TypeName>) });
    };
}
