use std::path::Path;

use toucan::{BindingOptions, Compiler, CompilerProfile, Config, RustTarget, Target};

const TARGETS: [Target; 2] = [
    Target::X86_64UnknownLinuxMusl,
    Target::Aarch64UnknownLinuxMusl,
];

#[test]
fn musl_targets_keep_their_linux_data_models_and_environment_guards() {
    for target in TARGETS {
        assert!(target.is_linux() && target.is_musl());
        assert_eq!(Target::parse(target.triple()).unwrap(), target);
        for compiler in [Compiler::Gnu, Compiler::Clang] {
            let profile = CompilerProfile::new(target, compiler).unwrap();
            let source = format!(
                "#if !defined(__linux__) || defined(__GLIBC__) || defined(__MUSL__)\n\
                 #error incorrect target predefines\n\
                 #endif\n\
                 #include <stddef.h>\n\
                 _Static_assert(sizeof(long)==8 && sizeof(void*)==8,\"LP64\");\n\
                 _Static_assert(sizeof(__builtin_va_list)=={},\"va_list\");\n\
                 _Static_assert(__LDBL_MANT_DIG__=={},\"long double format\");\n\
                 _Static_assert((char)-1{}0,\"plain char\");\n\
                 _Static_assert(_Generic((__WCHAR_TYPE__)0, {}:1,default:0),\"wchar\");\n\
                 struct Record {{ char tag; long value; }}; void call(struct Record*);",
                if target.is_aarch64() { 32 } else { 24 },
                if target.is_aarch64() { 113 } else { 64 },
                if target.is_aarch64() { ">" } else { "<" },
                if target.is_aarch64() {
                    "unsigned int"
                } else {
                    "int"
                },
            );
            let compilation =
                toucan::parse_source(Path::new("musl.h"), &source, &Config::with_profile(profile))
                    .unwrap();
            let (bindings, _) = compilation
                .bindings(&BindingOptions {
                    rust_target: RustTarget::RUST_1_64,
                    allowlist: vec!["Record".into(), "call".into()],
                    ..Default::default()
                })
                .unwrap();
            assert!(bindings.contains(&format!("Generated by Toucan for {}.", target.triple())));
            assert!(bindings.contains("target_env = \"musl\""));
            assert!(!bindings.contains("target_env = \"gnu\""));
        }
    }
}

#[test]
fn musl_bindings_preserve_unproved_call_abi_diagnostics() {
    for target in TARGETS {
        for compiler in [Compiler::Gnu, Compiler::Clang] {
            let config = Config::with_profile(CompilerProfile::new(target, compiler).unwrap());
            for (source, diagnostic) in [
                ("long double f(long double);", "long double by value"),
                (
                    "struct Bits { unsigned value:3; }; void f(struct Bits);",
                    "records containing bitfields",
                ),
                (
                    "typedef int V __attribute__((vector_size(16))); void f(V);",
                    "vectors and records containing vectors",
                ),
                (
                    "struct A { _Atomic int value; }; void f(struct A);",
                    "records containing atomic storage",
                ),
            ] {
                let unit = toucan::parse_source(Path::new("musl.h"), source, &config).unwrap();
                assert!(
                    unit.bindings(&BindingOptions::default())
                        .unwrap_err()
                        .to_string()
                        .contains(diagnostic)
                );
            }
            let narrow = toucan::parse_source(
                Path::new("musl.h"),
                "_Atomic signed char f(_Atomic signed char);",
                &config,
            )
            .unwrap();
            assert_eq!(
                narrow.bindings(&BindingOptions::default()).is_ok(),
                compiler == Compiler::Gnu
            );
        }
    }
}
